### ISSUE TITLE
Bulk example not working

### ISSUE THREAD

**Issue by justechn** [elastic/elasticsearch-js#1003]
## 💬 Questions and Help

I am new to the elasticserach-js library and I am trying to get the bulk api working. I am using the example found here https://github.com/elastic/elasticsearch-js/blob/master/docs/examples/asStream.asciidoc, but I am getting errors that I don't know how to fix. Here is my code 
```
const { body: bulkResponse } = await client.bulk({
    refresh: true,
    body: [
      // operation to perform
      { index: { _index: 'game-of-thrones' } },
      // the document to index
      {
        character: 'Ned Stark',
        quote: 'Winter is coming.'
      },

      { index: { _index: 'game-of-thrones' } },
      {
        character: 'Daenerys Targaryen',
        quote: 'I am the blood of the dragon.'
      },

      { index: { _index: 'game-of-thrones' } },
      {
        character: 'Tyrion Lannister',
        quote: 'A mind needs books like a sword needs a whetstone.'
      }
    ]
  });

  if (bulkResponse.errors) {
    console.log(bulkResponse);
    process.exit(1);
  }

  const { body: count } = await client.count({ index: 'tweets' });
  console.log(count)
``` 
and here is the response I get 
```
{ method: 'POST',
  path: '/_bulk',
  bulkBody: 
   [ { index: [Object] },
     { character: 'Ned Stark', quote: 'Winter is coming.' },
     { index: [Object] },
     { character: 'Daenerys Targaryen',
       quote: 'I am the blood of the dragon.' },
     { index: [Object] },
     { character: 'Tyrion Lannister',
       quote: 'A mind needs books like a sword needs a whetstone.' } ],
  querystring: { refresh: true } }
{ ResponseError: action_request_validation_exception
    at IncomingMessage.response.on (/Users/joltdev/Downloads/elasticsearch_aggregation/node_modules/@elastic/elasticsearch/lib/Transport.js:287:25)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'ResponseError',
  meta: 
   { body: { error: [Object], status: 400 },
     statusCode: 400,
     headers: 
      { 'content-type': 'application/json; charset=UTF-8',
        'content-length': '307' },
     warnings: null,
     meta: 
      { context: null,
        request: [Object],
        name: 'elasticsearch-js',
        connection: [Object],
        attempts: 0,
        aborted: false } } }
```
I don't know what `action_request_validation_exception` is or how to fix it. I have tried searching online, but have yet to find a solution. Any help would be appreciated. 
BTW I am using Node 8, and elasticsearch 6.6.0, and elasticsearch-js 7.4.0

**Comment by delvedor** [comment]
Hello!
The reason why the example is not working for you is that you are not defining the  `_type` along with the `_index`.
That example has been written for Elasticsearch v7, see also [this doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/removal-of-types.html) for further information.
Moreover, the client version should always be the same of Elasticasearch, so if you are using Elasticsearch `v6.6.0`, you should install the client v6. Take a look at our [compatibility documentation](https://github.com/elastic/elasticsearch-js#compatibility) :)
