### ISSUE TITLE
Problem with keepAlive

### ISSUE THREAD

**Issue by gansbrest** [elastic/elasticsearch-js#107]
While playing with this library and Hapi, I noticed errors with keepAlive ( default: true ).

Here is how I use it:

```
        var client = new elasticsearch.Client({
            host: 'localhost:9200',
            log: 'trace',
            keepAlive: false
        });

         // HAPI route handler
         item.handler = function(req, reply) {
            client.search({
                  q: 'pants'
            }).then(function(body) {
                // Dummy response
                reply(null, [{id: 2, bbb: "bob"}]);
            })
        };
```

I get following error:

Debug: hapi, internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'length' of undefined
    at CustomForeverAgent.<anonymous> (/home/gansbrest/Work/mirtrik-node-api/node_modules/elasticsearch/node_modules/forever-agent/index.js:26:34)
    at CustomForeverAgent.EventEmitter.emit (events.js:106:17)
    at Socket.onFree (http.js:1301:10)
    at Socket.EventEmitter.emit (events.js:92:17)
    at http.js:1722:14
    at process._tickDomainCallback (node.js:459:13)

which seem to be pointing to forever-agent module. A little debugging showed that self.sockets is empty, no matter how many were actually created. I didn't find the code which populates open sockets..

The other strange thing is that when I reach minSockets ( 10 by default ), I'm getting timeouts:

Elasticsearch DEBUG: 2014-05-30T20:57:36Z
  starting request { method: 'POST', path: '/_search', query: { q: 'pants' } }

Seems  like sockets are not released or something..

When I do `netstat -n A inet | grep 9200` I can see all 10 sockets in ESTABLISHED state.

What could be the reason of this strange behavior?

**Comment by jonahharris** [comment]
#371

**Comment by delvedor** [comment]
Hi! I'm closing this due to inactivity, if it is still an issue, please feel free to reopen! :)
