### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by penge** [elastic/elasticsearch-js#1156]
## 🐛 Bug Report

While fixing the test in https://github.com/elastic/elasticsearch-js/pull/1142 I have seen that `request()` in Transport creates a **Promise** that doesn't handle `UnhandledPromiseRejectionWarning` or in other words, doesn't handle `catch`

## To Reproduce

'Sniff interval' on the CI randomly failed. Easiest way to reproduce this was, if I called `client.info()` after the `shutdown()`.

The unhadled error looked as following:

```
(node:1013) UnhandledPromiseRejectionWarning: ConnectionError: connect ECONNREFUSED 127.0.0.1:40619
    at ClientRequest.<anonymous> (elasticsearch-js/lib/Connection.js:103:18)
    at ClientRequest.emit (events.js:210:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at emitUnhandledRejectionWarning (internal/process/promises.js:141:15)
    at processPromiseRejections (internal/process/promises.js:203:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

More in this log: https://github.com/elastic/elasticsearch-js/pull/1142/checks?check_run_id=583154405

**Comment by delvedor** [comment]
Can you write a code to reproduce this issues without using the test you are mentioning?
That test do not reflect a "real world" code, as it's written to trigger internal events of the client.

**Comment by penge** [comment]
I'll try

**Comment by penge** [comment]
@delvedor 
I haven't replicated this and got what would be expected if trying to sniff after the client is closed - `NoLivingConnectionsError: There are no living connections`.
I think we can close it for now.
