### ISSUE TITLE
Connection with id '${opts.id || opts.url.href}' is already present

### ISSUE THREAD

**Issue by zhengtulymGh** [elastic/elasticsearch-js#1191]
when I run app.ts, show erros:
```
******:demo ****$ npm run serve:dev

> voc-inner@1.0.0 serve:dev /Users/******/Documents/work/server/demo
> export NODE_ENV=dev || SET "NODE_ENV=dev" &&  nodemon --watch 'controllers/*' -e ts,tsx --exec ts-node --files app.ts

[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): controllers/**/*
[nodemon] watching extensions: ts,tsx
[nodemon] starting `ts-node --files app.ts`
[2020-05-13 20:48:21]
[2020-05-13 20:48:21] /Users/******/Documents/work/server/demo/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:87
      throw new Error(`Connection with id '${opts.id || opts.url.href}' is already present`)
            ^
[2020-05-13 20:48:21] Error: Connection with id 'http://*****:9200/' is already present
    at ConnectionPool.addConnection (/Users/******/Documents/work/server/demo/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:87:13)
    at /Users/******/Documents/work/server/demo/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:76:37
    at Array.forEach (<anonymous>)
    at ConnectionPool.addConnection (/Users/******/Documents/work/server/demo/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:76:19)
    at new Client (/Users/******/Documents/work/server/demo/node_modules/@elastic/elasticsearch/index.js:105:27)
    at Function.ES.getInstance (/Users/******/Documents/work/server/demo/services/es.ts:11:23)
    at Object.<anonymous> (/Users/******/Documents/work/server/demo/controllers/home.ts:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Module.m._compile (/Users/******/Documents/work/server/demo/node_modules/ts-node/src/index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/******/Documents/work/server/demo/node_modules/ts-node/src/index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/******/Documents/work/server/demo/routes/index.ts:2:1)
[nodemon] app crashed - waiting for file changes before starting...
```

// part of app.ts file
```js
import * as Server from './server';

async function start() {
    const app = Express();
    await Server.init();
    await initApp(app);

    //start server
    return new Promise(function (resolve, reject) {
        let projectConfig = config.getTyped('project');
        app.listen(projectConfig.webPort, (err) => {
            logger.info(`server is listening on ${projectConfig.webPort}`);
            logger.info(`server stated ... `);
            err ? reject(err) : resolve();
        });
    });
}

start().then(() => {
    logger.info(`server started`);
}).catch(err => {
    logger.error(`server error`);
    logger.error(err);
});
```

// part of server.ts file
```
import { config } from './config.service';

import { ES } from './services/es';

async function init() {
    try {
        console.log(`----connet mongo: ${config.getTyped('database')}----`);
        console.log(`----connet es: ${config.getTyped('esClientHost')}----`);
        await mongoose.connect(config.getTyped('database'), { useNewUrlParser: true });

        const client:any = ES.getInstance();
    } catch (error) {
        console.log(error)
    }
}

export {
    init
}
```

part of controllers/home.ts
```js
import nodeExcel = require("excel-export");
import Server = require('../server');
const request = require('request');
const moment = require('moment');
const logger = Server.logger.getLogger('main');

const maxAge = 60 * 60 * 10

export class HomeController {
    public static ins: HomeController;
    static getInstance(): HomeController {
        if (this.ins) {
            return this.ins;
        }

        this.ins = new HomeController();
        return this.ins;
    }

   public async exportMediaList(req: Express.Request, res: Express.Response, getList:Function,arr:Array<any>, next){
    try {
      let mongoDataList = await getList(req, res, next)
      console.log(mongoDataList,'mongoDataList')
      let conf:any = {cols:[],rows:[]};
      arr.forEach((item:any)=>{
        conf.cols.push({
          caption:item,
          type:'string'
        })
      })
        console.log(conf.cols,'conf.cols')
        mongoDataList.map(({_source})=>_source).forEach((item)=>{
          conf.rows.push([
            item["media_name"],
            item["media_url"],
            item["media_type"],
            item["priority"],
            `${item["create_user_account"]}-${item["create_user_name"]}`,
            item["update_time"],
            `${item["edit_user_account"]}-${item["edit_user_name"]}`,
            item["comment"]
          ])
        })
        console.log(conf.rows,'conf.rows')
        var result = nodeExcel.execute(conf);

        const date = moment(new Date()).format('YYYY/MM/DD HH:mm:ss');
        console.log(date,'date') 
        res.setHeader("Content-Disposition", "attachment; filename=list-"+(new Date().getTime())+".xlsx");  
        res.end(result, 'binary');
    } catch(error){
      return next(error)
    }
  }
}


interface ISearchOptions {
    title: string,  // vivo_voc_data
    keyword: String
}
```

**Comment by delvedor** [comment]
Hello! From the code you have added in the issue description, I can't tell what's wrong, as I can't see the client initialization.

Very likely, you are registering more than once the same connection.

**Comment by zhengtulymGh** [comment]
Thanks very much, I haved solved the problem
