### ISSUE TITLE
client.update throws document_missing_exception

### ISSUE THREAD

**Issue by bornagainraj7** [elastic/elasticsearch-js#1262]
I'm actually trying to create a log in elastic search for all the requests that are made, so with a middleware, I'm creating a document with code # 1 and once the operation is performed I'm trying to update that document with code # 2.

#PLEASE IGNORE THE LIBRARY DECLARATIONS AS I'VE ADDED IT IN THE REAL CODE

code # 1
```js


  const now = new Date();
  // const id = meaningful.random(meaningfulOption);
  const id = uuid.v4();

  if (req.method !== 'OPTIONS') {
    const { body } = req;

    if (body) {
      delete body.password;
      delete body.newPassword;
    }

    const data = {
      _id: id,
      reqId: id,
      method: req.method,
      userAgent: req.headers['user-agent'],
      originUrl: req.headers.origin,
      refererUrl: req.headers.referer,
      baseUrl: req.baseUrl,
      originalUrl: req.originalUrl,
      query: req.query,
      params: req.params,
      body: body,
      user: req.user,
      requestedOn: now,
      createdAt: now.getTime(),
    };
    esLib.routeLogger(data);
  }

  req.reqId = id;
  next();

```

code # 2

```js


  const updateStatus = {
    index: 'route',
    id: id,
    body: {
      // doc: data,
      script: {
        source: 'def docSrc = ctx._source; docSrc.respondedOn=params.respondedOn; docSrc.response=params.response;',
        lang: 'painless',
        params: data,
      },
    },
  };

  return new Promise((resolve, reject) => {
    client.update(updateStatus)
      .then((result) => {
        // logger.info(result);
        // logger.info(result.meta.request);
        resolve(result.meta.request);
      })
      .catch((error) => {
        logger.error(error);
        logger.error(error.meta.body.error);
        reject(new Error('ES_ERROR'));
      });
  });

```

At first I tried as below, and it worked fine with other Index.

```js

  const updateStatus = {
    index: 'route',
    id: id,
    body: {
      doc: data,
    },
  };

```

## Expected behavior

Now Some times it is successful but most of the time I get an error as Error # 1

Now when I go and see the data in Kibana v 7.7.1 I can see the document with the same _id

Error # 1
```js


2020-07-17T13:37:00+0530 <error> es.lib.js:397 () ResponseError: document_missing_exception
    at IncomingMessage.<anonymous> (D:\www\InSa\partners\partners-api\node_modules\@elastic\elasticsearch\lib\Transport.js:232:25)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'ResponseError',
  meta: {
    body: { error: [Object], status: 404 },
    statusCode: 404,
    headers: {
      'content-type': 'application/json; charset=UTF-8',
      'content-length': '393'
    },
    warnings: null,
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
2020-07-17T13:37:00+0530 <error> es.lib.js:398 () {
  root_cause: [
    {
      type: 'document_missing_exception',
      reason: '[_doc][7298a754-95ea-460c-b4c4-6259c2942d01]: document missing',
      index_uuid: 'eTJAu0bhRDSD5J_rjA45hA',
      shard: '0',
      index: 'route'
    }
  ],
  type: 'document_missing_exception',
  reason: '[_doc][7298a754-95ea-460c-b4c4-6259c2942d01]: document missing',
  index_uuid: 'eTJAu0bhRDSD5J_rjA45hA',
  shard: '0',
  index: 'route'
}

```

Kibana result
```js

{
        "_index" : "route",
        "_type" : "_doc",
        "_id" : "7298a754-95ea-460c-b4c4-6259c2942d01",
        "_score" : 1.0,
        "_source" : {
          "reqId" : "7298a754-95ea-460c-b4c4-6259c2942d01",
          "method" : "GET",
          "userAgent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
          "originUrl" : "someurl",
          "refererUrl" : "someurl",
          "baseUrl" : "someurl",
          "originalUrl" : "someurl",
          "query" : {
            "page" : "0",
            "size" : "10",
            "userId" : "5139977a-7074-4600-a7e7-8ac133ee9ec1"
          },
          "params" : { },
          "body" : { },
          "user" : {}
      }

```

NOTE: Is it because I'm trying to update it in a very short interval of time when it is not even created? If that is the case then what can be done for it?

## Your Environment

- *node version*: 12.13.0
- `@elastic/elasticsearch` *version*: >=7.7.1
- `Kibana` *version*: >=7.7.1
- *os*:Windows
- *any other relevant information*

**Comment by delvedor** [comment]
> NOTE: Is it because I'm trying to update it in a very short interval of time when it is not even created? If that is the case then what can be done for it?

Yes, very likely!
You should either call `client.indices.refresh({ index: 'route' })` between the two API calls or when you initially index the data, add the `refresh` parameter:

```js
await client.index({
  index: 'route',
  id: 'some-id',
  refresh: 'wait_for' 
})
```

**Comment by bornagainraj7** [comment]
So what should I write instead of 'wait_for', or is it just 'wait_for' ?

**Comment by delvedor** [comment]
Just `wait_for` :)
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html) you can find all the possible options. I recommend using `wait_for` as refreshing is an expensive operation.
