### ISSUE TITLE
Question of es 503 error message

### ISSUE THREAD

**Issue by dkswjdals89** [elastic/elasticsearch-js#1363]
### Please note that this issue tracker is not a help forum and this issue may be closed.

It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

Hello
503 error occurred due to ES down during request to Elastic Seach and error message sent by ES Client is `Unexpected token } in JSON at position 60`

I understand internally that if there is a 50X error, a request is made again, but I think it is probably due to a failed retry failure.

Could I receive the error message differently?
For example, `Server request failed - {HTTP_STATUS_CODE}`

Messages like `Unexpected token } in JSON at position 60` seem a little hard to understand at a glance.

I will attach a stack of error messages below.

```
DeserializationError: Unexpected token } in JSON at position 60
at Serializer.deserialize (/opt/service/node_modules/@elastic/elasticsearch/lib/Serializer.js:28:13)
at IncomingMessage.<anonymous> (/opt/service/node_modules/@elastic/elasticsearch/lib/Transport.js:223:43)
at /opt/service/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
at Scope._activate (/opt/service/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:53:14)
at Scope.activate (/opt/service/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
at IncomingMessage.bound (/opt/service/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
at IncomingMessage.emit (events.js:327:22)
at IncomingMessage.EventEmitter.emit (domain.js:483:12)
at endReadableNT (_stream_readable.js:1220:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

I am using is ES version 7.7 and the Client is using 7.9.1.
I'm asking for your help because I can't see the above issue.

Thank you.

**Comment by delvedor** [comment]
Hello! If you get a deserialization error, very likely the connection broke while reading the body.
The client provides better handling of that case in 7.10 (see also https://github.com/elastic/elasticsearch-js/pull/1343).
