### ISSUE TITLE
Cannot read property 'q' of null

### ISSUE THREAD

**Issue by bentoco** [elastic/elasticsearch-js#1366]
## 💬 Questions and Help

I've a AWS Lambda who get images by tags on elasticsearch. When I pass a existent tag via queryParams the API the below error was show. And I dont know what suppose to do. 

URL i.e.: https://api/dev/images?q=dog 

```
2020-11-30T17:37:35.072Z	c9a8365a-0307-49b9-9523-f7664f95cb7b	ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'q' of null",
    "stack": [
        "TypeError: Cannot read property 'q' of null",
        "    at Runtime.module.exports.get [as handler] (/var/task/handler.js:19:37)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

## Handler
```javascript
'use strict'

const elasticsearchService = require('./service/elasticsearchService')

module.exports.get = async (event) => {
    console.log(event)
    const data = await elasticsearchService.search(
        event.queryStringParameters.q
    )
    return {
        statusCode: 201,
        body: JSON.stringify(data),
    }
}
```

## Service
```javascript
const elasticsearch = require('elasticsearch')
const client = new elasticsearch.Client({
    host:
        'https://vpc-elasticsearch-cluster.us-east-1.es.amazonaws.com',
    apiVersion: '7.4',
})

const search = async (query) => {
    return await client.search({
        index: 'imagens',
        q: 'tags:' + query,
    })
}

module.exports = {
    search: search,
}
```
## Event
```
2020-11-30T17:37:35.070Z	c9a8365a-0307-49b9-9523-f7664f95cb7b	INFO	{
  resource: '/images',
  path: '/images',
  httpMethod: 'GET',
  headers: {
    Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.5',
    'CloudFront-Forwarded-Proto': 'https',
    'CloudFront-Is-Desktop-Viewer': 'true',
    'CloudFront-Is-Mobile-Viewer': 'false',
    'CloudFront-Is-SmartTV-Viewer': 'false',
    'CloudFront-Is-Tablet-Viewer': 'false',
    'CloudFront-Viewer-Country': 'BR',
    dnt: '1',
    Host: 'execute-api.us-east-1.amazonaws.com',
    'upgrade-insecure-requests': '1',
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0',
    Via: '2.0 ac4e6581409ee543d30418bc80eff8a8.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': 'gOlEG_Eg0wTnNdOQs4gIvFb9e2p97BHOVk_cyk04dTRwspn_3lOIFA==',
    'X-Amzn-Trace-Id': 'Root=1-5fc52dde-0cac29786d71ae6a509cfc95',
    'X-Forwarded-For': '191.13.134.245, 64.252.179.90',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https'
  },
  multiValueHeaders: {
    Accept: [
      'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
    ],
    'Accept-Encoding': [ 'gzip, deflate, br' ],
    'Accept-Language': [ 'en-US,en;q=0.5' ],
    'CloudFront-Forwarded-Proto': [ 'https' ],
    'CloudFront-Is-Desktop-Viewer': [ 'true' ],
    'CloudFront-Is-Mobile-Viewer': [ 'false' ],
    'CloudFront-Is-SmartTV-Viewer': [ 'false' ],
    'CloudFront-Is-Tablet-Viewer': [ 'false' ],
    'CloudFront-Viewer-Country': [ 'BR' ],
    dnt: [ '1' ],
    Host: [ execute-api.us-east-1.amazonaws.com' ],
    'upgrade-insecure-requests': [ '1' ],
    'User-Agent': [
      'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0'
    ],
    Via: [
      '2.0 ac4e6581409ee543d30418bc80eff8a8.cloudfront.net (CloudFront)'
    ],
    'X-Amz-Cf-Id': [ 'gOlEG_Eg0wTnNdOQs4gIvFb9e2p97BHOVk_cyk04dTRwspn_3lOIFA==' ],
    'X-Amzn-Trace-Id': [ 'Root=1-5fc52dde-0cac29786d71ae6a509cfc95' ],
    'X-Forwarded-For': [ '191.13.134.245, 64.252.179.90' ],
    'X-Forwarded-Port': [ '443' ],
    'X-Forwarded-Proto': [ 'https' ]
  },
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    resourceId: 'igpxv0',
    resourcePath: '/images',
    httpMethod: 'GET',
    extendedRequestId: 'W1QawEAJoAMF7og=',
    requestTime: '30/Nov/2020:17:37:34 +0000',
    path: '/dev/images',
    accountId: '661087684535',
    protocol: 'HTTP/1.1',
    stage: 'dev',
    domainPrefix: '9nuer2',
    requestTimeEpoch: 1606757854312,
    requestId: 'c89e7ced-fb72-442d-b5e9-7fed00d59197',
    identity: {
      cognitoIdentityPoolId: null,
      accountId: null,
      cognitoIdentityId: null,
      caller: null,
      sourceIp: '191.13.134.245',
      principalOrgId: null,
      accessKey: null,
      cognitoAuthenticationType: null,
      cognitoAuthenticationProvider: null,
      userArn: null,
      userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0',
      user: null
    },
    domainName: '.execute-api.us-east-1.amazonaws.com',
    apiId: '9nvml'
  },
  body: null,
  isBase64Encoded: false
}
```

**Comment by delvedor** [comment]
Hello! This looks like an issue with Lambda and not the Elasticsearch client, I recommend you to open an issue in the appropriate Lambda issue tracker.
