### ISSUE TITLE
Error connecting to Elastic Cloud with apikey, works fine with username and password

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/elasticsearch-js#1410]
## 🐛 Bug Report

When I authenticate via APIkey I see this error:
`ResponseError: security_exception at Unzip.onBody [as cb]` 
(full error later on)

## To Reproduce

- Create Elastic Cloud deployment
- Add the cloud ID, username (elastic), and password to the game of thrones example in README.md
- verify that it works
- Create an API Key
- concatenate the ID and key like so: `echo -n 'KB35A3gXXXX_Lhmonwr:xqr1iNZiQXXXX-0qCCdkA' | base64`
- Replace the username and password with the base64 encoded concatenated ID and API Key
- see the error

Paste your code here:

```js
'use strict'

const { Client } = require('@elastic/elasticsearch')
/* const client = new Client({ node: 'http://localhost:9200' }) */
const client = new Client({
  cloud: {
    id: "elastic-observability-deployment:ZWFzdHVzMi5henVyZS5lbGFzdGljLWNsb3VkLmNvbTo5XXXjZjlhN2Q2MzliMzViMWMwNWIwJGUwMjgzM2M0MDY2MzQwYWE4ODI2ZDI5M2IxY2JmZGVl"
  },
  auth: {
    apikey: 'S0IzNUEzZ0JaRTJSX0xobWXXXXI6eHFyMWlOWmlRZnFNQmMtMHFDQ2RrQQ=='
  }
})

async function run () {
  // Let's start by indexing some data
  await client.index({
    index: 'game-of-thrones',
    // type: '_doc', // uncomment this line if you are using Elasticsearch ≤ 6
    body: {
      character: 'Ned Stark',
      quote: 'Winter is coming.'
    }
  })

  await client.index({
    index: 'game-of-thrones',
    // type: '_doc', // uncomment this line if you are using Elasticsearch ≤ 6
    body: {
      character: 'Daenerys Targaryen',
      quote: 'I am the blood of the dragon.'
    }
  })

  await client.index({
    index: 'game-of-thrones',
    // type: '_doc', // uncomment this line if you are using Elasticsearch ≤ 6
    body: {
      character: 'Tyrion Lannister',
      quote: 'A mind needs books like a sword needs a whetstone.'
    }
  })

  // here we are forcing an index refresh, otherwise we will not
  // get any result in the consequent search
  await client.indices.refresh({ index: 'game-of-thrones' })

  // Let's search!
  const { body } = await client.search({
    index: 'game-of-thrones',
    // type: '_doc', // uncomment this line if you are using Elasticsearch ≤ 6
    body: {
      query: {
        match: { quote: 'winter' }
      }
    }
  })

  console.log(body.hits.hits)
}

run().catch(console.log)

```

Full error:
```
ResponseError: security_exception
    at Unzip.onBody [as cb] (/Users/droscigno/GitHub/elasticsearch-nodejs/node_modules/@elastic/elasticsearch/lib/Transport.js:333:23)
    at Unzip.zlibBufferOnEnd (zlib.js:152:10)
    at Unzip.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  meta: {
    body: { error: [Object], status: 401 },
    statusCode: 401,
    headers: {
      'content-encoding': 'gzip',
      'content-length': '209',
      'content-type': 'application/json; charset=UTF-8',
      'www-authenticate': 'Basic realm="security" charset="UTF-8", Bearer realm="security", ApiKey',
      'x-cloud-request-id': 'TXB8DgBNQUmkVnYKn_WuoA',
      'x-found-handling-cluster': '5973a4f9642c4cf9a7d639b35b1c05b0',
      'x-found-handling-instance': 'instance-0000000001',
      date: 'Fri, 05 Mar 2021 20:43:43 GMT'
    },
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
```

Here is the first API Key I tried.  I based it off of the roles needed for Metricbeat:
```
POST /_security/api_key
{
  "name": "nodejs_example",
  "role_descriptors": {
    "nodejs_example_writer": {
      "cluster": ["monitor"],
      "index": [
        {
          "names": ["game-of-thrones"],
          "privileges": ["view_index_metadata", "create_index", "write", "create_doc", "read"]
        }
      ]
    }
  }
}
```

Next I tried giving all privy at both cluster and index levels:
```
PUT /_security/api_key
{
  "name": "nodejs_example2",
  "role_descriptors": {
    "nodejs_example_writer": {
      "cluster": ["all"],
      "index": [
        {
          "names": ["*"],
          "privileges": ["all"]
        }
      ]
    }
  }
}
```

And then I tried skipping the roles, as then I should get the same privy as the logged in user (elastic):
```
PUT /_security/api_key
{
  "name": "my-api-key22",
  "expiration": "1d"
}
```

## Expected behavior

Paste the results here:
This is the proper output:

```js
[
  {
    _index: 'game-of-thrones',
    _type: '_doc',
    _id: 'DBzq_ncBZE2R_LhmSSTs',
    _score: 1.3840476,
    _source: { character: 'Ned Stark', quote: 'Winter is coming.' }
  }
]

```

## Your Environment

- *node version*: v14.16.0
- `@elastic/elasticsearch` *version*: >=7.11.1 (in Elastic Cloud)
- *os*: Mac

**Comment by delvedor** [comment]
Hello! There is a typo in your configuration, you wrote `apikey` (all lowercase) instead of `apiKey`.

**Comment by DanRoscigno** [comment]
Thanks so much!!
