### ISSUE TITLE
Better async/await error handling: show full details

### ISSUE THREAD

**Issue by hansott** [elastic/elasticsearch-js#1432]
## 🚀  Feature Proposal

Show full error details when using `await` / `async` in TypeScript:

```ts
import { Client } from "@elastic/elasticsearch";

class SomeClass {
  constructor(private readonly elastic: Client) {}

  async removeUserActivity(
    businessId: BusinessId,
    userId: UnifiedUserId
  ): Promise<void> {
    const index = await this.getActivityIndex(businessId);

    await this.elastic.delete_by_query({
      index: index,
      refresh: true,
      body: {
        query: {
          bool: {
            must: [
              { term: { "identifiers.user_ids": userId.asString() } },
            ],
          },
        },
      },
    });
  }
}
```

When something is wrong, we just see `ResponseError: parsing_exception` (e.g. when `terms` should be `term`)

```
(node:19773) UnhandledPromiseRejectionWarning: ResponseError: parsing_exception
    at onBody (/home/demir/Desktop/Journy.io/journy-io/server/node_modules/@elastic/elasticsearch/lib/Transport.js:311:23)
    at IncomingMessage.onEnd (/home/demir/Desktop/Journy.io/journy-io/server/node_modules/@elastic/elasticsearch/lib/Transport.js:240:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:529:15)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

To see the full error we have to wrap `await this.elastic.delete_by_query({ ... })` inside a `try/catch` and re-throw the `Error`.

This also happens for other methods: `await this.elastic.search({ ... })` etc

**Comment by delvedor** [comment]
Hello! We are aware of this issue, and it will be fixed in version 8.
We are working to see if it can be fixed in v7 as well. Thanks for reporting!

**Comment by hansott** [comment]
Thanks @delvedor 🥳

**Comment by hansott** [comment]
@delvedor is this fixed in v8?
