### ISSUE TITLE
Error ib/Helpers.js:75   async * scrollSearch (params, options = {}) - wingston logger integration

### ISSUE THREAD

**Issue by vaibhavpatil-symblai** [elastic/elasticsearch-js#1560]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `not reproducible` label.**

## To Reproduce
Use node - version **nvm use v8.9.4** 
Run 
https://www.npmjs.com/package/winston-elasticsearch
Paste your code here:

```js

```

## Expected behavior

Paste the results here:

    at tryModuleLoad (module.js:506:12) {"error":{},"stack":"/Users/vaishnavi/Documents/workspace/prs/conversation-api/node_modules/winston-elasticsearch/node_modules/@elastic/elasticsearch/lib/Helpers.js:75\n  async * scrollSearch (params, options = {}) {\n        ^\n\nSyntaxError: Unexpected token *\n    at createScript (vm.js:80:10)\n    at Object.runInThisContext (vm.js:139:10)\n    at Module._compile (module.js:617:28)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Module.require (module.js:597:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/Users/vaishnavi/Documents/workspace/prs/conversation-api/node_modules/winston-elasticsearch/node_modules/@elastic/elasticsearch/index.js:28:17)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Module.require (module.js:597:17)\n    at requ

## Your Environment

- *node version*: 
- `@elastic/elasticsearch` *version*: >=8.9.4
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by vaibhavpatil-symblai** [comment]
async * scrollSearch (params, options = {}) {
    if (this[kMetaHeader] !== null) {
      options.headers = options.headers || {}
      options.headers['x-elastic-client-meta'] = this[kMetaHeader] + ',h=s'
    }

**Comment by vaibhavpatil-symblai** [comment]
This is breaking change not backward compatible

**Comment by delvedor** [comment]
Hello!
It looks like you are using an older version of Node.js (v8 perhaps?), which is [not supported](https://github.com/elastic/elasticsearch-js#nodejs-support) by this client.

**Comment by dwzhanglong** [comment]
my project not work，as the same problem
[https://github.com/elastic/elasticsearch-js/issues/1603](url)
