### ISSUE TITLE
Unable to run the tests on master branch

### ISSUE THREAD

**Issue by nelsonic** [elastic/elasticsearch-js#158]
Trying to run `grunt test` or `grunt test_unit` on Ubuntu (using Vagrant) - all dependencies installed - I get the error:

``` sh
installing es
1.4_nightly installed

Running "run:es_1.4" (run) task
>> es_1.4 started
/bin/sh: 1: ./.snapshots/1.4_nightly/bin/elasticsearch: not found

Running "mochacov:integration_1.4" (mochacov) task

  ․

  0 passing (15s)
  1 failing

  1) integration "before all" hook:
     Error: unable to establish contact with ES
      at /vagrant/elasticsearch-js/test/integration/yaml_suite/client_manager.js:42:16
      at respond (/vagrant/elasticsearch-js/src/lib/transport.js:254:9)
      at sendReqWithConnection (/vagrant/elasticsearch-js/src/lib/transport.js:174:7)
      at next (/vagrant/elasticsearch-js/src/lib/connection_pool.js:213:7)
      at process._tickCallback (node.js:419:13)



Warning:  Use --force to continue.

Aborted due to warnings.
```

Screenshot:

![unable-to-run-tests](https://cloud.githubusercontent.com/assets/194400/5061920/86731274-6da4-11e4-97b8-31f12464be2c.png)

**Comment by delvedor** [comment]
Hi! I'm closing this due to inactivity, if it is still an issue, please feel free to reopen! :)
