### ISSUE TITLE
v8.2.0 has broken bulk API

### ISSUE THREAD

**Issue by lluked** [elastic/elasticsearch-js#1691]
## 🐛 Bug Report

v8.2.0 has broken the Bulk API function.

## To Reproduce

Using https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/bulk_examples.html 

With package.json:
```
{
  "dependencies": {
    "@elastic/elasticsearch": "8.2.0",
    "array.prototype.flatmap": "^1.2.5",
    "get-json": "^1.0.1"    
  }
}
```

run `npm init`

execute the JavaScript in the documentation 

response is:

```
ResponseError: illegal_argument_exception: [illegal_argument_exception] Reason: The bulk request must be terminated by a newline [\n]
    at SniffingTransport.request (/home/luke/Projects/nfl-elastic-aggregations/es-import/node_modules/@elastic/transport/lib/Transport.js:476:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.BulkApi [as bulk] (/home/luke/Projects/nfl-elastic-aggregations/es-import/node_modules/@elastic/elasticsearch/lib/api/api/bulk.js:51:12)
    at async run (/home/luke/Projects/nfl-elastic-aggregations/es-import/javascripts/bulk_example.js:58:24) {
  meta: {
    body: { error: [Object], status: 400 },
    statusCode: 400,
    headers: {
      'x-elastic-product': 'Elasticsearch',
      'content-type': 'application/json;charset=utf-8',
      'content-length': '245'
    },
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    },
    warnings: [Getter]
  }
```

Deleting the node_modules folder, pinning "@elastic/elasticsearch" to `8.1.0`, running `node install` and running the JavaScript again results in a successful call with the response being:

```
{
  count: 5,
  _shards: { total: 1, successful: 1, skipped: 0, failed: 0 }
}
```

To double check the `node_modules` folder was deleted and `8.2.0` was used again resulting in the same error as before.

## Your Environment

- *node version*: v16.15.0
- `@elastic/elasticsearch` *version*: 8.2.0
- *os*: Ubuntu 20.04 host with Elasticsearch docker image being used

**Comment by onzag** [comment]
I was just getting that error right now wondering what was wrong, can confirm it's occurring to me too in what used to be successful, it's all over my logs.

Equally the error occurs inside docker.

I am also getting a strange 11 abort listeners memory leak or something.

**Comment by lluked** [comment]
> I was just getting that error right now wondering what was wrong, can confirm it's occurring to me too in what used to be successful, it's all over my logs.
> 
> Equally the error occurs inside docker.
> 
> I am also getting a strange 11 abort listeners memory leak or something.
> 
> #1686

Thanks, I missed that as the issue had been closed and GitHub defaults to only showing open issues. It looks like it is still an issue though as it has not been updated yet on npm. I'll leave this open for whoever wants to close it but it may be worth leaving a issue open until the npm packages are updated to stop someone else from raising again.

**Comment by ddolcimascolo** [comment]
Yeah, I asked @delvedor about that in the other issue. We've been hit by that also

David

**Comment by jparish3** [comment]
I have had the same experience after upgrading to 8.2 & wish I had checked here earlier. A related issue occurs using the docs code to create the example tweets index: 
client.indices.create throws this error:[illegal_argument_exception] Reason: request [/tweets] contains unrecognized parameter: [operations]

**Comment by jparish3** [comment]
Using this search string 'The bulk request must be terminated by a newline [\\n]' does not lead to the closed issue [#1686](https://github.com/elastic/elasticsearch-js/issues/1686) but produces results like [this](https://discuss.elastic.co/t/elasticsearch-bulk-error-must-be-terminated-by-a-newline/299037) that creates more confusion around the issue.

**Comment by lluked** [comment]
> Using this search string 'The bulk request must be terminated by a newline [\\n]' does not lead to the closed issue [#1686](https://github.com/elastic/elasticsearch-js/issues/1686) but produces results like [this](https://discuss.elastic.co/t/elasticsearch-bulk-error-must-be-terminated-by-a-newline/299037) that creates more confusion around the issue.

This is the same issue as [#1686](https://github.com/elastic/elasticsearch-js/issues/1686) if you read the error message, which was closed because it is going to be fixed in a new release, really it should have been left open until it was actually fixed.

I haven't looked at the other issue in the Elasticsearch discuss thread in detail but that is using  curl and the suggestion was to change the header type. 

Reading [#1686](https://github.com/elastic/elasticsearch-js/issues/1686) it appears the header type for the Bulk API was changed to text breaking its current use. As far as I can tell the header type cannot be set manually with the API as it is hardcoded.

They are similar issues but the discuss forum post looks to be user error in data formatting and header type, whereas this is something a user cannot fix as the header type cannot be changed by the user and data is being submitted in the defined standard according to documentation.

**Comment by jparish3** [comment]
I think thats right. I tested using 'Content-Type': 'application/x-ndjson' & the new line but got this Error: bulk helper: the datasource must be an array or a buffer or a readable stream or an async generator
I am using a google cloud functions/next.js proxy to communicate with the client, so the initial post request looks similar to curl. I eventually went to docs example for testing, but as noted earlier, the sample code threw errors for 'create index' that could be fixed by removing certain commands. I thought perhaps the docs were out of sync, but the came across the issue. thanks for re-opening this

**Comment by Jeffrey-Zutt** [comment]
We experience the same issue.
Rolling back to 8.1.0 resolves it for now

**Comment by delvedor** [comment]
Hello! We can't release an "official" patch release yet, as the client must follow the Stack release versioning.
However, we have released a custom patch version just for `v8.2.0` to unblock you as quickly as possible.
You should expect to see a definitive `v8.2.1` in a few days.
https://www.npmjs.com/package/@elastic/elasticsearch/v/8.2.0-patch.1

You can install it by running `npm i @elastic/elasticsearch`, make sure that the version installed is `8.2.0-patch.1`.

**Comment by lluked** [comment]
> 

Thanks, npm still pulls `8.2.0` instead of `8.2.0-patch.1` when defining the dependency as `"@elastic/elasticsearch": "^8.0.0"`, is this expected? Seeing as `8.2.0` is broken it may as well be set to pull `8.2.0-patch.1` as the latest version.

**Comment by delvedor** [comment]
If npm cannot pick up the update out of the box, try to uninstall the client an install it again.
The patch is being distributed with the `latest` tag and npm should install it automatically.

**Comment by ddolcimascolo** [comment]
Hey @delvedor

Elasticsearch 8.2.1 was released. When are you planning to release the JS client including this fix?

Thx,
David

**Comment by delvedor** [comment]
`v8.2.1` is out, thank you for your patience!
Please upgrade to this version.
