### ISSUE TITLE
Elastic client will exit whole process while occur error

### ISSUE THREAD

**Issue by joebnb** [elastic/elasticsearch-js#1810]
![image](https://user-images.githubusercontent.com/1646883/215409715-bd77354a-6ab8-4c94-893d-7c754ed3b61a.png)

if elastic service not ready,it will exit whole process,which i expect just throw a error, that es not working

**Comment by JoshMock** [comment]
@joebnb can you give more details about what version of the client you're using and platform you're running on?

**Comment by joebnb** [comment]
thanks for attention
this is init elastic scripts and it works if elastic service is runing
![image](https://user-images.githubusercontent.com/1646883/234448198-ad6aa433-a066-488e-a523-6aa8055033e1.png)

this is usecase in my code

![image](https://user-images.githubusercontent.com/1646883/234448307-cf0fbf3c-8135-491a-9533-ee58d40b8862.png)

try catch not work

![image](https://user-images.githubusercontent.com/1646883/234448408-cf91ce80-4b9a-4d8c-8056-05bb4be7d0f2.png)

**Comment by JoshMock** [comment]
Your process is actually exiting healthy and doing what you've told it to do: log the error when `elastic.putScript` throws an exception. That exception you're logging is the `ECONNREFUSED` text in your screenshot. If you were to add some lines of code at the end of `initScript` it would still execute.

If you don't wrap the call to `putScript` in a try/catch, the error output will be even longer, like so:

```
/home/joshmock/Code/throwaway/node_modules/@elastic/transport/lib/Transport.js:528
                            : new errors_1.ConnectionError(error.message, result);
                              ^

ConnectionError: connect ECONNREFUSED ::1:9200
    at SniffingTransport.request (/home/joshmock/Code/throwaway/node_modules/@elastic/transport/lib/Transport.js:528:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.PutScriptApi [as putScript] (/home/joshmock/Code/throwaway/node_modules/@elastic/elasticsearch/lib/api/api/put_script.js:58:12)
    at async initScript (/home/joshmock/Code/throwaway/index.js:16:5) {
  meta: {
    body: undefined,
    statusCode: 0,
    headers: {},
    meta: {
      context: null,
      request: {
        params: {
          method: 'PUT',
          path: '/_scripts/foo',
          body: '{"script":{"lang":"painless","source":"int total = 0; total += 1; return total;"}}',
          querystring: '',
          headers: {
            'user-agent': 'elastic-transport-js/8.3.1 (linux 6.2.12-arch1-1-x64; Node.js v18.15.0)',
            'x-elastic-client-meta': 'es=8.6.0,js=18.15.0,t=8.3.1,hc=18.15.0',
            'content-type': 'application/vnd.elasticsearch+json; compatible-with=8',
            accept: 'application/vnd.elasticsearch+json; compatible-with=8',
            'content-length': '82'
          }
        },
        options: {},
        id: 1
      },
      name: 'elasticsearch-js',
      connection: Connection {
        url: <ref *1> URL {
          [Symbol(context)]: URLContext {
            flags: 400,
            scheme: 'http:',
            username: '',
            password: '',
            host: 'localhost',
            port: 9200,
            path: [Array],
            query: null,
            fragment: null
          },
          [Symbol(query)]: URLSearchParams {
            [Symbol(query)]: [],
            [Symbol(context)]: [Circular *1]
          }
        },
        tls: null,
        id: 'http://localhost:9200/',
        timeout: 30000,
        headers: {},
        deadCount: 0,
        resurrectTimeout: 0,
        _openRequests: 0,
        weight: 1000,
        pool: <ref *2> Pool {
          _events: [Object: null prototype] {},
          _eventsCount: 0,
          _maxListeners: undefined,
          [Symbol(kCapture)]: false,
          [Symbol(destroyed)]: false,
          [Symbol(onDestroyed)]: null,
          [Symbol(closed)]: false,
          [Symbol(onClosed)]: [],
          [Symbol(queue)]: FixedQueue {
            tail: [FixedCircularBuffer],
            head: [FixedCircularBuffer]
          },
          [Symbol(clients)]: [ [Client], [Client] ],
          [Symbol(queued)]: 0,
          [Symbol(onDrain)]: [Function: onDrain],
          [Symbol(onConnect)]: [Function (anonymous)],
          [Symbol(onDisconnect)]: [Function (anonymous)],
          [Symbol(onConnectionError)]: [Function (anonymous)],
          [Symbol(stats)]: PoolStats { [Symbol(pool)]: [Circular *2] },
          [Symbol(dispatch interceptors)]: [],
          [Symbol(connections)]: 256,
          [Symbol(url)]: URL {
            [Symbol(context)]: [URLContext],
            [Symbol(query)]: [URLSearchParams]
          },
          [Symbol(options)]: {
            keepAliveTimeout: 600000,
            keepAliveMaxTimeout: 600000,
            keepAliveTimeoutThreshold: 1000,
            pipelining: 1,
            maxHeaderSize: 16384,
            headersTimeout: 30000,
            bodyTimeout: 30000,
            connect: [Function: connect],
            interceptors: undefined
          },
          [Symbol(factory)]: [Function: defaultFactory],
          [Symbol(Intercepted Dispatch)]: [Function: [dispatch]],
          [Symbol(needDrain)]: false
        },
        [Symbol(status)]: 'alive',
        [Symbol(ca fingerprint)]: null,
        [Symbol(diagnostics)]: Diagnostic {
          _events: [Object: null prototype] {},
          _eventsCount: 0,
          _maxListeners: undefined,
          [Symbol(kCapture)]: false
        },
        [Symbol(event emitter)]: EventEmitter {
          _events: [Object: null prototype] {},
          _eventsCount: 0,
          _maxListeners: undefined,
          [Symbol(kCapture)]: false
        }
      },
      attempts: 3,
      aborted: false
    },
    warnings: [Getter]
  }
}

Node.js v18.15.0
```

You can also tell whether the exception made the process exit or not by the process's exit status code. In Bash you can print that via `echo $?`.

Running your code like so: `node index.js; echo $?` prints `0`, a healthy exit code. If you run `putScript` without a try/catch, the same command will print `1`, an error exit code, meaning that the uncaught exception is what exited the process.
