### ISSUE TITLE
Need ability to test connection without producing a backtrace

### ISSUE THREAD

**Issue by blakemcbride** [elastic/elasticsearch-js#183]
Greetings,

I am using Node/JavaScript to access elasticsearch.  I am using the 1.4 API.

If a connection fails (using new elasticsearch.Client(...)), the 'new' succeeds.  You don't know the connection failed till you try to use it.  Okay, I can live with that.  What I can't live with is the backtrace I get when I try to use it rather than just an error return.  I need a way of validating a connection without producing a backtrace or exception.

I get no error when I connect (to the wrong port). But I get the following when I try to use it:

Elasticsearch ERROR: 2015-01-23T17:14:40Z Error: Request error, retrying -- connect ECONNREFUSED at Log.error (/home/blake/ComponentServer/node_modules/elasticsearch/src/lib/log.js:213:60) at checkRespForFailure (/home/blake/ComponentServer/node_modules/elasticsearch/src/lib/transport.js:195:18) at HttpConnector.<anonymous> (/home/blake/ComponentServer/node_modules/elasticsearch/src/lib/connectors/http.js:154:7) at ClientRequest.bound (/home/blake/ComponentServer/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17) at ClientRequest.emit (events.js:95:17) at Socket.socketErrorListener (http.js:1552:9) at Socket.emit (events.js:95:17) at net.js:441:14 at process._tickCallback (node.js:442:13) Elasticsearch WARNING: 2015-01-23T17:14:40Z Unable to revive connection: http://localhost:920/ Elasticsearch WARNING: 2015-01-23T17:14:40Z No living connections error: No Living connections

I tried using client.cluster.health and client.ping with the same results.

Thanks for the help!

Blake McBride

**Comment by delvedor** [comment]
Hi! I'm closing this due to inactivity, if it is still an issue, please feel free to reopen! :)
