### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by coldlamper** [elastic/elasticsearch-js#207]
I'm trying to do a bulk import of about 55000 rows.

```
console.log('Bulk indexing...');
client.bulk(bulkData)
.then(
    console.log('Done ');
)
```

After a few seconds the console outputs

```
Bulk indexing
warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
...
```

repeating the warning many times then "RangeError: Maximum call stack size exceeded" at the end.
I'm using node 0.10.38.

Adding
```
process.nextTick = function(arguments) {
	setImmediate(arguments);
};
```
at the beginning allows the script to complete and indexes the rows.

Can anyone think of a more proper way way to fix this? Thanks.

**Comment by spalger** [comment]
Can you do me a favor and try submitting less documents? If the number of documents is causing the issue I would be surprised. Can you also submit more information about the bulkData you are sending (format, data type) and the surrounding code? Thanks

**Comment by coldlamper** [comment]
Less documents actually works , 40000 works, 45000 doesn't.

A row is structured like this
```
var person = {
	ID: row.ID,
	name: row.name,
	name_ngram: row.name_ngram,
	category_name: row.category_name,
	contact_first_name: row.contact_first_name,
	contact_last_name: row.contact_last_name,
	overview: row.overview,
	datetime_added: row.datetime_added,
	listings: []
}
data[row.ID] = person;
var listing = {
	ID: row.ID,
	locations_cities_ID: row.locations_cities_ID,
	location: {
		lat: row.latitude,
		lon: row.longitude
	},
	city_name: row.city_name
}
data[row.ID].listings.push(listing);
```
We construct the bulk data like this and try index with this function.


```
var indexData = function (data, new_index) {
		return new Promise(function (resolve, reject) {
			var bulkData = {
				body: [],
				requestTimeout: 240000
			};

			data.forEach(function (row) {
				bulkData.body.push({index: {_index: new_index, _type: 'clients', _id: row.ID}});
				bulkData.body.push(row);
			});
			console.time("bulk indexing");

			var indices = '';

			client.bulk(bulkData)
				.then(function (resp) {
					console.timeEnd("bulk indexing");
					console.log('Indexed ' + resp.items.length + ' documents');
					console.log('Aliasing... ');
					return client.indices.getAlias({name: 'clients'});
				})
				.then(function (resp) {
					resolve();
				})
				.catch(function (e) {
					reject(e)
				})
		})
	}
```

**Comment by anonrig** [comment]
Any progress?

**Comment by spalger** [comment]
@anonrig are you getting `RangeError: Maximum call stack size exceeded`? Can you provide a stack trace?

**Comment by timini** [comment]
```
/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:65
Log.prototype.listenerCount = function (event) {
                                       ^

RangeError: Maximum call stack size exceeded
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:65:40)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/Users/tim/Workspace/repositive/api.repositive.io/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
```

**Comment by spalger** [comment]
@timini you are hitting https://github.com/elastic/elasticsearch-js/issues/265. Please upgrade your elasticsearch-js

**Comment by suver** [comment]
thk, it`s good advice
