### ISSUE TITLE
Requirejs with Elasticsearch Angular app throwing "lib/connectors/angular" has not been loaded yet for context: _. Use require([])

### ISSUE THREAD

**Issue by nithyanv** [elastic/elasticsearch-js#211]
I am trying to build Elasticsearch Angular app. I am using require.js.

main.js

    require.config({
 
    paths : {
    'angular' : '../bower_components/angular/angular',
    'elasticsearch' : '../node_modules/elasticsearch/src/elasticsearch.angular',
    'app' : 'app',
    'coreModule':'coreModule',
    'esClient' : 'service/esClient'
    },
    
    shim : {
        
    'app':{
    'deps' : ['angular','coreModule']
    },
        
    'coreModule' : {
    'deps' :['angular', 'elasticsearch','esClient']   
    },
        
    'esClient' : {
    'deps' :['angular', 'elasticsearch']   
    }
        
    }
    
    });

    require(['app'], function(){
   
    angular.bootstrap(document, ['app']); 
    });

esClient.js

    define(function(){
 
    var esClient=angular.module('esClient', ['elasticsearch']);

    esClient.service('client', function (esFactory) {
    return esFactory({
    host: 'http://localhost:9200',
    apiVersion: '1.5',
    log: 'trace'
    });
    });
    
    });
------

But it is throwing the following errors. Anyone else faced this issue?

Uncaught Error: Module name "lib/connectors/angular" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
makeError @ require.js:166
localRequire @ require.js:1407
requirejs @ require.js:1752
(anonymous function) @ elasticsearch.angular.js:7
coreModule.js:3 coreModule module
app.js:4 App module
angular.js:63 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module coreModule due to:
Error: [$injector:modulerr] Failed to instantiate module esClient due to:
Error: [$injector:modulerr] Failed to instantiate module elasticsearch due to:
Error: [$injector:nomod] Module 'elasticsearch' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

PS : I previous used bower installed elasticsearch. Now using npm install. Hence the updated comment.

**Comment by spalger** [comment]
Sorry, the node package doesn't support browser use right now. You should use the elasticsearch-browser[0] module if you want to use npm, or the bower one. 

[0] https://www.npmjs.com/package/elasticsearch-browser

**Comment by nithyanv** [comment]
I did use the bower one earlier. But I found a different set of errors being thrown when I did that.

I had raised that on stackoverflow (link below). There the issue seemed to be Uncaught TypeError: _.extend is not a function ( _.extend function used in elasticsearch.angular.js, which was installed through bower )

http://stackoverflow.com/questions/29844317/elasticsearch-angular-app-throwing-uncaught-typeerror-extend-is-not-a-functio 

It works great without requirejs as a simple angularjs app. But we need requirejs to manage our dependencies. I couldn't any working sample of this. Surely, developers must be using it.

**Comment by jhiemer** [comment]
Having the same issue over here.

**Comment by spalger** [comment]
@nithyanv, we use the angular.js version of the browser client with require.js in https://github.com/elastic/kibana.

Pretty sure it just works but there may be more to it.

**Comment by jhiemer** [comment]
@spalger could you point me to the version you are using?

**Comment by jhiemer** [comment]
Hi, tried some further settings. The nearest point I got to working version is, when it stops me with:

```bash
Uncaught TypeError: _.isPlainObject is not a function
bootstrap.js - called
Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:modulerr] Failed to instantiate module services due to:
Error: [$injector:modulerr] Failed to instantiate module elasticsearch due to:
Error: [$injector:nomod] Module 'elasticsearch' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.15/$injector/nomod?p0=elasticsearch
    at REGEX_STRING_REGEXP (http://localhost:8000/lib/angular/angular.js?v=0.1:63:12)
    at http://localhost:8000/lib/angular/angular.js?v=0.1:1774:17
    at ensure (http://localhost:8000/lib/angular/angular.js?v=0.1:1698:38)
    at module (http://localhost:8000/lib/angular/angular.js?v=0.1:1772:14)
    at http://localhost:8000/lib/angular/angular.js?v=0.1:4115:22
    at forEach (http://localhost:8000/lib/angular/angular.js?v=0.1:323:20)
    at loadModules (http://localhost:8000/lib/angular/angular.js?v=0.1:4099:5)
    at http://localhost:8000/lib/angular/angular.js?v=0.1:4116:40
    at forEach (http://localhost:8000/lib/angular/angular.js?v=0.1:323:20)
    at loadModules (http://localhost:8000/lib/angular/angular.js?v=0.1:4099:5)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=elasticsearch&p1=E…3A%2F%2Flocalhost%3A8000%2Flib%2Fangular%2Fangular.js%3Fv%3D0.1%3A4099%3A5)
    at REGEX_STRING_REGEXP (http://localhost:8000/lib/angular/angular.js?v=0.1:63:12)
    at http://localhost:8000/lib/angular/angular.js?v=0.1:4138:15
    at forEach (http://localhost:8000/lib/angular/angular.js?v=0.1:323:20)
    at loadModules (http://localhost:8000/lib/angular/angular.js?v=0.1:4099:5)
    at http://localhost:8000/lib/angular/angular.js?v=0.1:4116:40
    at forEach (http://localhost:8000/lib/angular/angular.js?v=0.1:323:20)
    at loadModules (http://localhost:8000/lib/angular/angular.js?v=0.1:4099:5)
    at http://localhost:8000/lib/angular/angular.js?v=0.1:4116:40
    at forEach (http://localhost:8000/lib/angular/angular.js?v=0.1:323:20)
    at loadModules (http://localhost:8000/lib/angular/angular.js?v=0.1:4099:5)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=services&p1=Error%…3A%2F%2Flocalhost%3A8000%2Flib%2Fangular%2Fangular.js%3Fv%3D0.1%3A4099%3A5)
    at REGEX_STRING_REGEXP (http://localhost:8000/lib/angular/angular.js?v=0.1:63:12)
    at http://localhost:8000/lib/angular/angular.js?v=0.1:4138:15
    at forEach (http://localhost:8000/lib/angular/angular.js?v=0.1:323:20)
    at loadModules (http://localhost:8000/lib/angular/angular.js?v=0.1:4099:5)
    at http://localhost:8000/lib/angular/angular.js?v=0.1:4116:40
    at forEach (http://localhost:8000/lib/angular/angular.js?v=0.1:323:20)
    at loadModules (http://localhost:8000/lib/angular/angular.js?v=0.1:4099:5)
    at createInjector (http://localhost:8000/lib/angular/angular.js?v=0.1:4025:11)
    at doBootstrap (http://localhost:8000/lib/angular/angular.js?v=0.1:1452:20)
    at Object.bootstrap (http://localhost:8000/lib/angular/angular.js?v=0.1:1473:12)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=myApp&p1=Error%3A%…A%2F%2Flocalhost%3A8000%2Flib%2Fangular%2Fangular.js%3Fv%3D0.1%3A1473%3A12)
    at REGEX_STRING_REGEXP (http://localhost:8000/lib/angular/angular.js?v=0.1:63:12)
    at http://localhost:8000/lib/angular/angular.js?v=0.1:4138:15
    at forEach (http://localhost:8000/lib/angular/angular.js?v=0.1:323:20)
    at loadModules (http://localhost:8000/lib/angular/angular.js?v=0.1:4099:5)
    at createInjector (http://localhost:8000/lib/angular/angular.js?v=0.1:4025:11)
    at doBootstrap (http://localhost:8000/lib/angular/angular.js?v=0.1:1452:20)
    at Object.bootstrap (http://localhost:8000/lib/angular/angular.js?v=0.1:1473:12)
    at http://localhost:8000/js/bootstrap.js?v=0.1:12:15
    at Object.context.execCb (http://localhost:8000/lib/requirejs/require.js:1665:33)
    at Object.Module.check (http://localhost:8000/lib/requirejs/require.js:874:51)
```

**Comment by spalger** [comment]
@jhiemer we are using the latest 3.0, I just installed the latest 4.0 version and am seeing the same error. Expect a fix shortly.

**Comment by spalger** [comment]
@jhiemer I just published 4.1.0, can you try it out and tell me how it goes?

**Comment by jhiemer** [comment]
Works fine! Thx. :-)

**Comment by nithyanv** [comment]
@jhiemer No. I haven't found a solution yet for this. For the moment, I am using native $http of Angularjs to interact with ES directly. I am sure this will take a performance hit. @spalger I will check with the angularjs used by Kibana.
