### ISSUE TITLE
Scroll Id too long

### ISSUE THREAD

**Issue by osman** [elastic/elasticsearch-js#220]
My cluster has roughly 1500 shards. When trying to scan and scroll through the entire cluster, we get an error saying that the looks like this

```
Elasticsearch ERROR: 2015-05-22T19:16:42Z
  Error: Request complete with error -- socket hang up
      at Log.error (/home/osman/node_modules/elasticsearch-tools/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/home/osman/node_modules/elasticsearch-tools/node_modules/elasticsearch/src/lib/transport.js:197:18)
      at HttpConnector.<anonymous> (/home/osman/node_modules/elasticsearch-tools/node_modules/elasticsearch/src/lib/connectors/http.js:146:7)
      at ClientRequest.bound (/home/osman/node_modules/elasticsearch-tools/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)
      at ClientRequest.emit (events.js:95:17)
      at Socket.socketOnEnd [as onend] (http.js:1573:9)
      at Socket.g (events.js:180:16)
      at Socket.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:442:13)


  error: {"message":{"code":"ECONNRESET"}}
```

Upon further research, it looks like the scroll id is tied to the number of shards that you are scrolling through and there doesn't seem to be a way for the scroll id to be put into the request body in the node.js API, which would fix the issue.

**Comment by spalger** [comment]
Which version of the client are you using? Recent versions should put the scrollId into the body rather than the url.

As a workaround, you can just change the key from `scrollId:` to `body:`

**Comment by osman** [comment]
Thanks for the quick reply. We are actually using a node tool, which is using the API. I just checked their dependencies file, and the version looks to be `2.4.0`.

For the workaround, what is the syntax for moving scrollId into body? I was looking for some docs before and wasn't able to find anything.

**Comment by fabiano-amaral** [comment]
i'm with the same problem.

js client `"@elastic/elasticsearch": "6.8.4",`

**Comment by delvedor** [comment]
@fabiano-amaral if you pass the `scroll_id` in the body, you will solve the issue :)

**Comment by fabiano-amaral** [comment]
> @fabiano-amaral if you pass the `scroll_id` in the body, you will solve the issue :)

Works with DELETE requests too?

Thanks!

**Comment by delvedor** [comment]
It should!
