### ISSUE TITLE
require('elasticsearch') fails with undefined is not a function error

### ISSUE THREAD

**Issue by muralisa** [elastic/elasticsearch-js#233]
src/node_modules/elasticsearch/src/lib/errors.js:23
_.inherits(ErrorAbstract, Error);
  ^
TypeError: undefined is not a function
    at Object.<anonymous> (/path/src/node_modules/elasticsearch/src/lib/errors.js:23:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.cls_wrapMethod (/path/src/node_modules/newrelic/lib/shimmer.js:228:38)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/path/src/node_modules/elasticsearch/src/lib/transport.js:8:14)
    at Module._compile (module.js:460:26)

**Comment by Martin-Luther** [comment]
Same kind of problem when trying to require('elasticsearch'). I have installed the module via NPM. I am using node version 0.12.4, elasticsearch-js version 5.0.0 and here is what I get :

```tty
TypeError: undefined is not a function
    at /Users/martin/Documents/www/airliquide/sigma/node_modules/elasticsearch/node_modules/lodash/index.js:12288:15
    at /Users/martin/Documents/www/airliquide/sigma/node_modules/elasticsearch/node_modules/lodash/index.js:3073:15
    at baseForOwn (/Users/martin/Documents/www/airliquide/sigma/node_modules/elasticsearch/node_modules/lodash/index.js:2046:14)
    at runInContext (/Users/martin/Documents/www/airliquide/sigma/node_modules/elasticsearch/node_modules/lodash/index.js:12282:5)
    at Object. (/Users/martin/Documents/www/airliquide/sigma/node_modules/elasticsearch/node_modules/lodash/index.js:12320:11)
    at Object. (/Users/martin/Documents/www/airliquide/sigma/node_modules/elasticsearch/node_modules/lodash/index.js:12351:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
