### ISSUE TITLE
Index API error on node

### ISSUE THREAD

**Issue by shelllbyyyyyy** [elastic/elasticsearch-js#2525]
### Question

hey i make request index api on my project node backend (nest js) 

i've got an error TypeError: Cannot read properties of undefined (reading 'toString')
    at Client.CreateApi (D:path\node_modules\.pnpm\@elastic+elasticsearch@8.16.2\node_modules\@elastic\src\api\api\create.ts:68:52)
    at SearchService.index (D:path\apps\server\dist\main.js:5325:49)
    at ESProfileRepositoryImpl.save (D:path\apps\server\dist\main.js:3891:49)
    at CreateProfileHandler.execute (D:path\apps\server\dist\main.js:1690:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ProfileController.createProfile (D:path\apps\server\dist\main.js:4569:28)

this is my document to index
{
  id: '1e58c971-4eaa-416b-8383-1943d944c686',
  user_id: 'e5ba5397-f7a4-4432-88c3-7d4f5f1aea80',
  profile_name: 'test',
  avatar_url: 'https://test/profile-picture/f9ltabrhkj8pwe8uygip.jpg',
  created_at: 2024-12-05T22:02:25.049Z,
  updated_at: 2024-12-05T22:02:25.049Z
}

and this is my mapping 
export const mapping: estypes.IndicesPutMappingRequest = {
  index: `${PROFILE_INDEX}_v1`,
  date_detection: true,
  dynamic: false,
  dynamic_date_formats: ['yyyy-MM-dd HH:mm:ss', 'yyyy-MM-dd'],
  numeric_detection: true,
  properties: {
    id: { type: 'keyword' },
    user_id: { type: 'keyword' },
    profile_name: { type: 'text' },
    avatar_url: { type: 'text' },
    created_at: {
      type: 'date',
    },
    updated_at: {
      type: 'date',
    },
  },
};

and this is my function to index api
async save(data: ProfileEntity): Promise<ProfileEntity> {
    const doc = ProfileFactory.toResponse(data);

    const result = await this.searchService.index(
      this.profilesIndex,
      data.getId.getValue,
      doc,
    );

    if (!result._id) return null;

    this.logger.log('Create document success');

    return data;
  }

public async index<T>(
    index: string,
    id: string,
    document: T,
  ): Promise<estypes.IndexResponse> {
    try {
      const result = await this.esService.create({
        index,
        id,
        document,
      });

      return result;
    } catch (error) {
      throw error;
    }
  }

please someone help me
my elastic run on docker compose elasticsearch:8.15.4
and my dependencies use "@elastic/elasticsearch": "^8.16.2"

**Comment by shelllbyyyyyy** [comment]
hey i just delete toString() on node_modules and it works

from this:
if (params.index != null && params.id != null) {
        method = 'PUT';
        path = `/${encodeURIComponent(params.index.toString())}/_doc/${encodeURIComponent(params.id.toString())}`;
    }
    else {
        method = 'POST';
        path = `/${encodeURIComponent(params.index.toString())}/_doc`;
    }

to this:
 if (params.index != null && params.id != null) {
        method = 'PUT';
        path = `/${encodeURIComponent(params.index)}/_doc/${encodeURIComponent(params.id)}`;
    }
    else {
        method = 'POST';
        path = `/${encodeURIComponent(params.index)}/_doc`;
    }

**Comment by shelllbyyyyyy** [comment]
solved

it turns out , i just typo on index 
private readonly profilesIndex:  'profiles';
instead of 
private readonly profilesIndex = 'profiles';
lol 😂
