### ISSUE TITLE
Does not work with latest node.

### ISSUE THREAD

**Issue by saksham0808** [elastic/elasticsearch-js#291]
The last version I got this to work with was 0.12
Since then, here is the error I get when I launch my application
```
/home/somepath/node_modules/elasticsearch/src/lib/log.js:65
Log.prototype.listenerCount = function (event) {
                                       ^

RangeError: Maximum call stack size exceeded
    at Log.listenerCount (/home/somepath/node_modules/elasticsearch/src/lib/log.js:65:40)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/home/somepath/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/home/somepath/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/home/somepath/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/home/somepath/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/home/somepath/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/home/somepath/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/home/somepath/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
events.js:141
      throw er; // Unhandled 'error' event
      ^
```

I've been using it since long by downgrading my version. That's getting more and more troublesome as time passes.

**Comment by saksham0808** [comment]
Well I just realized this has been fixed. I don't understand though, why are we relying on things like
```
  // node >= 3.0 supports EE#listenerCount()
  if (EventEmitter.prototype.listenerCount) {
    return EventEmitter.prototype.listenerCount.call(this, event);
  }

  // compatability for node < 0.10
  if (EventEmitter.listenerCount) {
    return EventEmitter.listenerCount(this, event);
  }
```
in log.js file?
That's what broke this with the shift to node 5.0.0
