### ISSUE TITLE
clearScroll Unhandled rejection Error: Not Found

### ISSUE THREAD

**Issue by RicherdLee** [elastic/elasticsearch-js#311]
Hi,when i use then method clear,there is a error
Unhandled rejection Error: Not Found
    at respond (/Users/haoli/Documents/nodejsworkspace/ESModel/node_modules/elasticsearch/src/lib/transport.js:260:15)
    at checkRespForFailure (/Users/haoli/Documents/nodejsworkspace/ESModel/node_modules/elasticsearch/src/lib/transport.js:219:7)
    at HttpConnector.<anonymous> (/Users/haoli/Documents/nodejsworkspace/ESModel/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/Users/haoli/Documents/nodejsworkspace/ESModel/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

could you do me a favor,thank you very much

**Comment by spalger** [comment]
Not Found errors happen when you are specifying a resource that elasticsearch doesn't know about. This isn't something I can really help with. Sorry
