### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by kadishmal** [elastic/elasticsearch-js#313]
Perhaps for some reason ES sends an empty response which results in the following error.

	 RangeError: Invalid string length
	     at IncomingMessage.<anonymous> (/home/user/indexer-1.0.0/node_modules/elasticsearch/src/lib/connectors/http.js:171:34)
	     at emitOne (events.js:77:13)
	     at IncomingMessage.emit (events.js:169:7)
	     at readableAddChunk (_stream_readable.js:146:16)
	     at IncomingMessage.Readable.push (_stream_readable.js:110:10)
	     at HTTPParser.parserOnBody (_http_common.js:109:22)
	     at Socket.socketOnData (_http_client.js:311:20)
	     at emitOne (events.js:77:13)
	     at Socket.emit (events.js:169:7)
	     at readableAddChunk (_stream_readable.js:146:16)
	     at Socket.Readable.push (_stream_readable.js:110:10)
	     at TCP.onread (net.js:523:20)

It happens in the following code:

    request = this.hand.request(reqParams, function (_incoming) {
        ...
        incoming.on('data', function (d) {
    ==>       response += d;
        });
        ...

This happens with Node `v5.0.0` and `elasticsearch` module `v10.0.1`.

**Comment by kadishmal** [comment]
It seems to be related to the [Out Of Memory](https://github.com/nodejs/node-v0.x-archive/issues/14170) issue when creating a string out of the large ES response. The solution was to decrease the number of hits to return by ES on scan.
