### ISSUE TITLE
TypeError when creating new document

### ISSUE THREAD

**Issue by mcdonnelldean** [elastic/elasticsearch-js#379]
I seem to be getting the following error when trying to add or update an index,

```
[TypeError: Cannot read property 'request' of undefined]
```

Code to create or update:

``` js
  var data = msg.data
  var name = data.name

  var client = opts.elastic.client
  var index = client.index
  var payload = {
    index: 'modules',
    type: "document",
    id: name,
    body: {
      name: name,
      detail: name,
      suggest: {
        input: name.split("-"),
        output: name
      }
    }
  }

  index(payload, (err, resp) => {
    console.log(err, resp)

    done()
  })
```

Creating the index,

```js
  opts.elastic.client = new ElasticSearch.Client({
    host: opts.host,
    port: opts.port
  })

  var client = opts.elastic.client
  var index = client.indices
  var mapping = {
    index: 'modules',
    type: "document",
    body: {
      properties: {
        name: {
          type: "string"
        },
        detail: {
          type: "object"
        },
        suggest: {
          type: "completion",
          analyzer: "simple",
          search_analyzer: "simple"
        }
      }
    }
  }

  index.exists({index: 'modules'}, (err, exists) => {
    if (err) return done(err)
    if (exists) return done()

    index.create({index: 'modules'}, (err) => {
      if (err) return done(err)

      index.putMapping(mapping, (err) => {
        done(err)
      })
    })
  })
```

```
"elasticsearch": "10.1.3"
```

**Comment by mcdonnelldean** [comment]
Hmmm, using `client.index` works so it's something to do with my assignment to a variable. Either way, not really a bug.

**Comment by tuanlc** [comment]
Hello,
I encountered the same problem, the error is:
`[CLI] ERROR TypeError: Cannot read property 'request' of undefined                                       
    at exec (src/lib/client_action.js:351:19)                                                                 
    at action (src/lib/client_action.js:60:16)`

I tried to debug and find out that in file `src/lib/client_action.js`, the `exec` function is called before the function:

```javascript
exports.namespaceFactory = function () {
  function ClientNamespace(transport) {
    this.transport = transport;
  }

  ClientNamespace.prototype = new exports.ApiNamespace();

  return ClientNamespace;
};
```
to set `this.transport`. So that why we have error `request of undefined` at line 351:
`return transport.request(request, cb);`

It seems I miss some things here? Could you please confirm this? 
Thanks a lot.
