### ISSUE TITLE
Using create returns 409 for deleted document - but undeletes the document.

### ISSUE THREAD

**Issue by BohoCode** [elastic/elasticsearch-js#434]
I have a document that has been deleted. If I GET the document it returns a 404.

If I then call create with the same document ID I get a 409 - document_already_exists_exception. Furthermore, the document is actually created, with it's index incremented and a GET will return the document! 

So calling create does what I would expect it to here, i.e. index the deleted document and increment it's version, but it returns a 409 error so the client believes that the document has failed to be created. 

```
  contributions-area-tests testing createEntry() +0ms
  contributions-area-tests requiring elasticSearchPersistence... +1ms
Elasticsearch INFO: 2016-08-09T14:34:06Z
  Adding connection to http://localhost:9200/

Elasticsearch DEBUG: 2016-08-09T14:34:06Z
  starting request { path: '/_nodes/_all/clear', method: 'GET' }


  contributions-area-tests calling createEntry() +209ms
  contributions-area Calling client.create() +0ms
Elasticsearch DEBUG: 2016-08-09T14:34:06Z
  starting request { method: 'POST',
    path: '/market-place/catalogEntry/test%20description',
    body: { title: 'blah', description: 'test description' },
    query: { op_type: 'create' } }


Elasticsearch TRACE: 2016-08-09T14:34:06Z
  -> GET http://localhost:9200/_nodes/_all/clear

  <- 200
  {
    "cluster_name": "elasticsearch",
    "nodes": {
      "dx2v4x6eSF6iE2bAfcygGA": {
        "name": "Meteorite",
        "transport_address": "127.0.0.1:9300",
        "host": "127.0.0.1",
        "ip": "127.0.0.1",
        "version": "2.3.4",
        "build": "e455fd0",
        "http_address": "127.0.0.1:9200"
      }
    }
  }

Elasticsearch DEBUG: 2016-08-09T14:34:06Z
  Request complete

Elasticsearch INFO: 2016-08-09T14:34:06Z
  Adding connection to http://127.0.0.1:9200/

Elasticsearch TRACE: 2016-08-09T14:34:06Z
  -> POST http://localhost:9200/market-place/catalogEntry/test%20description?op_type=create
  {
    "title": "blah",
    "description": "test description"
  }
  <- 0


Elasticsearch ERROR: 2016-08-09T14:34:06Z
  Error: Request error, retrying
  POST http://localhost:9200/market-place/catalogEntry/test%20description?op_type=create => socket hang up
      at Log.error (/Users/jamiebowen/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/jamiebowen/node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (/Users/jamiebowen/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (/Users/jamiebowen/node_modules/lodash/index.js:3095:19)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketCloseListener (_http_client.js:284:9)
      at emitOne (events.js:101:20)
      at Socket.emit (events.js:188:7)
      at TCP._handle.close [as _onclose] (net.js:492:12)

Elasticsearch TRACE: 2016-08-09T14:34:06Z
  -> POST http://127.0.0.1:9200/market-place/catalogEntry/test%20description?op_type=create
  {
    "title": "blah",
    "description": "test description"
  }
  <- 409
  {
    "error": {
      "root_cause": [
        {
          "type": "document_already_exists_exception",
          "reason": "[catalogEntry][test description]: document already exists",
          "shard": "3",
          "index": "market-place"
        }
      ],
      "type": "document_already_exists_exception",
      "reason": "[catalogEntry][test description]: document already exists",
      "shard": "3",
      "index": "market-place"
    },
    "status": 409
  }

Elasticsearch DEBUG: 2016-08-09T14:34:06Z
  Request complete

  contributions-area Error creating document in elasticsearch: [document_already_exists_exception] [catalogEntry][test description]: document already exists, with { shard=3 index=market-place } :: {"path":"/market-place/catalogEntry/test%20description","query":{"op_type":"create"},"body":"{\"title\":\"blah\",\"description\":\"test description\"}","statusCode":409,"response":"{\"error\":{\"root_cause\":[{\"type\":\"document_already_exists_exception\",\"reason\":\"[catalogEntry][test description]: document already exists\",\"shard\":\"3\",\"index\":\"market-place\"}],\"type\":\"document_already_exists_exception\",\"reason\":\"[catalogEntry][test description]: document already exists\",\"shard\":\"3\",\"index\":\"market-place\"},\"status\":409}"} +29ms


curl -i -XGET http://localhost:9200/market-place/catalogEntry/test%20description
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 160

{"_index":"market-place","_type":"catalogEntry","_id":"test description","_version":10,"found":true,"_source":{"title":"blah","description":"test description"}}
```

Using elasticsearch.js 11.0.1.

Elasticsearch details;
{
"name" : "Meteorite",
"cluster_name" : "elasticsearch",
"version" : {
"number" : "2.3.4",
"build_hash" : "e455fd0c13dceca8dbbdbb1665d068ae55dabe3f",
"build_timestamp" : "2016-06-30T11:24:31Z",
"build_snapshot" : false,
"lucene_version" : "5.5.0"
},
"tagline" : "You Know, for Search"
}

I'm new to elasticsearch and elasticsearch.js so I could be missing something here. Appreciate any pointers you could give.

**Comment by BohoCode** [comment]
Using elasticsearch.js 11.0.1. 

Elasticsearch details;
{
  "name" : "Meteorite",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.4",
    "build_hash" : "e455fd0c13dceca8dbbdbb1665d068ae55dabe3f",
    "build_timestamp" : "2016-06-30T11:24:31Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}

I'm new to elasticsearch and elasticsearch.js so I could be missing something here. Appreciate any pointers you could give.

**Comment by spalger** [comment]
Hey @BohoCode, sorry this sat for so long. This is caused by the client's retry behavior. When a request to elasticsearch does not complete successfully (no response was received) it is assumed to have not reached elasticsearch and retried. This is generally okay, and mostly helpful, but in your scenario it looks like the first create request must have actually made it to elasticsearch but the response just didn't make it back:

```
Elasticsearch TRACE: 2016-08-09T14:34:06Z
  -> POST http://localhost:9200/market-place/catalogEntry/test%20description?op_type=create
  {
    "title": "blah",
    "description": "test description"
  }
  <- 0
```

If you want to disable retries you can set the `maxRetries` configuration value to `0`.
