### ISSUE TITLE
How to listen for elasticsearch errors using javascript client?

### ISSUE THREAD

**Issue by ravilimbodiya** [elastic/elasticsearch-js#455]
Hi Team,

I am using elasticsearch in node JS as javascript client. I want to listen the error events in my node JS app, when elasticsearch suddenly goes down or it never started. Could you please let me know any way to handle these errors specially connection errors. 

This is how I'm creating a javascript client in node JS app-
_var client = new elasticsearch.Client({
    requestTimeout: 5000
});_

ERROR ON CONSOLE - 

Elasticsearch ERROR: 2016-10-18T20:52:25Z
  Error: Request error, retrying
  HEAD http://localhost:9200/INDEX_NAME => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (PROJECT_DIR/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (PROJECT_DIR/node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (PROJECT_DIR/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (PROJECT_DIR/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at emitOne (events.js:77:13)
      at ClientRequest.emit (events.js:169:7)
      at Socket.socketErrorListener (_http_client.js:269:9)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at emitErrorNT (net.js:1269:8)

Elasticsearch WARNING: 2016-10-18T20:52:25Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2016-10-18T20:52:25Z
  No living connections

{ [Error: No Living connections] message: 'No Living connections' }

Thanks!

**Comment by spalger** [comment]
These errors are sent back using either callbacks or promises on each call to the client. See https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-conventions.html#api-conventions-cb for more info
