### ISSUE TITLE
Integration tests failure (YamlDoc)

### ISSUE THREAD

**Issue by xtuc** [elastic/elasticsearch-js#462]
Got the following error : `Error: expected 'YamlDoc#version' to be a function` when trying to run `npm test`.

Am I missing a dependency ?

I use `master` branch from `elasticsearch-js`.

See full output:
```
> elasticsearch@12.0.1 test /Users/u/d/elasticsearch-js
> grunt test
[4mRunning "test" task
[24m
[4mRunning "run:generate" (run) task
[24m
src/_elasticsearch_ $ git remote set-url origin https://github.com/elastic/elasticsearch.git
----
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_0_90.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_1_0.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_1_1.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_1_2.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_1_3.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_1_4.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_1_5.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_1_6.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_1_7.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_2_0.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_2_1.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_2_2.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_2_3.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/api_methods_2_4.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/configuration.asciidoc
$ rm -rf /Users/u/d/elasticsearch-js/docs/index.asciidoc
$ rm -rf src/lib/apis/0_90.js
$ rm -rf src/lib/apis/1_0.js
$ rm -rf src/lib/apis/1_1.js
$ rm -rf src/lib/apis/1_2.js
$ rm -rf src/lib/apis/1_3.js
$ rm -rf src/lib/apis/1_4.js
$ rm -rf src/lib/apis/1_5.js
$ rm -rf src/lib/apis/1_6.js
$ rm -rf src/lib/apis/1_7.js
$ rm -rf src/lib/apis/2_0.js
$ rm -rf src/lib/apis/2_1.js
$ rm -rf src/lib/apis/2_2.js
$ rm -rf src/lib/apis/2_3.js
$ rm -rf src/lib/apis/2_4.js
$ rm -rf src/lib/apis/5_0.js
$ rm -rf src/lib/apis/5_x.js
$ rm -rf src/lib/apis/browser_index.js
$ rm -rf src/lib/apis/index.js
$ rm -rf src/lib/apis/master.js
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_0_90
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_0
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_1
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_2
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_3
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_4
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_5
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_6
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_7
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_2_0
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_2_1
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_2_2
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_2_3
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_2_4
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_5_0
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_5_x
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_master
----
src/_elasticsearch_ $ git fetch --no-tags --force origin 5.0:5.0 2.4:2.4 2.3:2.3 2.2:2.2 2.1:2.1 2.0:2.0 1.7:1.7 1.6:1.6 1.5:1.5 1.4:1.4 1.3:1.3 1.2:1.2 1.1:1.1 1.0:1.0 0.90:0.90 5.x:5.x master:master
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_5_0
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_5_0
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_5_0.tar 5.0 rest-api-spec/src/main/resources/rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_5_0.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_5_0 --strip-components 4
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_5_0.tar
wrote 120 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/5_0.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_5_0.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_5_0.js
wrote 5.0 method docs to /Users/u/d/elasticsearch-js/docs/api_methods.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_2_4
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_2_4
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_2_4.tar 2.4 rest-api-spec/src/main/resources/rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_2_4.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_2_4 --strip-components 4
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_2_4.tar
wrote 114 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/2_4.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_2_4.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_2_4.js
wrote 2.4 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_2_4.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_2_3
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_2_3
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_2_3.tar 2.3 rest-api-spec/src/main/resources/rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_2_3.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_2_3 --strip-components 4
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_2_3.tar
wrote 113 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/2_3.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_2_3.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_2_3.js
wrote 2.3 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_2_3.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_2_2
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_2_2
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_2_2.tar 2.2 rest-api-spec/src/main/resources/rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_2_2.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_2_2 --strip-components 4
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_2_2.tar
wrote 109 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/2_2.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_2_2.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_2_2.js
wrote 2.2 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_2_2.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_2_1
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_2_1
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_2_1.tar 2.1 rest-api-spec/src/main/resources/rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_2_1.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_2_1 --strip-components 4
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_2_1.tar
wrote 109 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/2_1.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_2_1.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_2_1.js
wrote 2.1 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_2_1.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_2_0
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_2_0
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_2_0.tar 2.0 rest-api-spec/src/main/resources/rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_2_0.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_2_0 --strip-components 4
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_2_0.tar
wrote 106 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/2_0.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_2_0.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_2_0.js
wrote 2.0 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_2_0.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_7
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_1_7
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_1_7.tar 1.7 rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_1_7.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_1_7 --strip-components 0
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_1_7.tar
wrote 108 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/1_7.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_1_7.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_1_7.js
wrote 1.7 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_1_7.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_6
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_1_6
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_1_6.tar 1.6 rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_1_6.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_1_6 --strip-components 0
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_1_6.tar
wrote 108 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/1_6.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_1_6.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_1_6.js
wrote 1.6 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_1_6.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_5
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_1_5
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_1_5.tar 1.5 rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_1_5.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_1_5 --strip-components 0
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_1_5.tar
wrote 106 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/1_5.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_1_5.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_1_5.js
wrote 1.5 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_1_5.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_4
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_1_4
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_1_4.tar 1.4 rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_1_4.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_1_4 --strip-components 0
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_1_4.tar
wrote 106 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/1_4.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_1_4.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_1_4.js
wrote 1.4 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_1_4.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_3
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_1_3
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_1_3.tar 1.3 rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_1_3.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_1_3 --strip-components 0
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_1_3.tar
wrote 101 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/1_3.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_1_3.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_1_3.js
wrote 1.3 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_1_3.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_2
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_1_2
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_1_2.tar 1.2 rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_1_2.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_1_2 --strip-components 0
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_1_2.tar
wrote 94 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/1_2.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_1_2.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_1_2.js
wrote 1.2 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_1_2.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_1
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_1_1
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_1_1.tar 1.1 rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_1_1.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_1_1 --strip-components 0
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_1_1.tar
wrote 94 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/1_1.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_1_1.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_1_1.js
wrote 1.1 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_1_1.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_1_0
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_1_0
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_1_0.tar 1.0 rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_1_0.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_1_0 --strip-components 0
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_1_0.tar
wrote 90 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/1_0.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_1_0.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_1_0.js
wrote 1.0 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_1_0.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_0_90
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_0_90
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_0_90.tar 0.90 rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_0_90.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_0_90 --strip-components 0
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_0_90.tar
wrote 64 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/0_90.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_0_90.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_0_90.js
wrote 0.90 method docs to /Users/u/d/elasticsearch-js/docs/api_methods_0_90.asciidoc
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_5_x
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_5_x
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_5_x.tar 5.x rest-api-spec/src/main/resources/rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_5_x.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_5_x --strip-components 4
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_5_x.tar
wrote 121 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/5_x.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_5_x.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_5_x.js
----
$ rm -rf /Users/u/d/elasticsearch-js/src/_elasticsearch_master
$ mkdir /Users/u/d/elasticsearch-js/src/_elasticsearch_master
src/_elasticsearch_ $ git archive --format tar --output /Users/u/d/elasticsearch-js/src/_elasticsearch_master.tar master rest-api-spec/src/main/resources/rest-api-spec
$ tar -x -f /Users/u/d/elasticsearch-js/src/_elasticsearch_master.tar -C /Users/u/d/elasticsearch-js/src/_elasticsearch_master --strip-components 4
$ rm /Users/u/d/elasticsearch-js/src/_elasticsearch_master.tar
wrote 121 api actions to /Users/u/d/elasticsearch-js/src/lib/apis/master.js
wrote YAML tests as JSON to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_tests_master.json
wrote YAML index to /Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_master.js
----
wrote api index to /Users/u/d/elasticsearch-js/src/lib/apis/index.js
wrote browser api index to /Users/u/d/elasticsearch-js/src/lib/apis/browser_index.js
----
wrote doc index to /Users/u/d/elasticsearch-js/docs/index.asciidoc
----
wrote configuration docs to /Users/u/d/elasticsearch-js/docs/configuration.asciidoc
----
[4mRunning "mochacov:unit" (mochacov) task
[24m
  584 passing (2s)
[4mRunning "esvm:5.0" (esvm) task
[24m
starting up "5.0" cluster
[32mINFO
[39m -  - cluster - Downloading & installing from "5.0" branch.
[32mINFO
[39m -  - cluster - Installing plugins
[32mINFO
[39m -  - cluster - Starting 1 nodes
[32mINFO
[39m -  - cluster - esvm log level configuration disabled
[32mINFO
[39m - elasticsearch_js_test_runner - node - initializing ...
[32mINFO
[39m - elasticsearch_js_test_runner - node_environment - using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [70.3gb], net total_space [232.6gb], spins? [unknown], types [hfs]
[32mINFO
[39m - elasticsearch_js_test_runner - node_environment - heap size [1.9gb], compressed ordinary object pointers [true]
[32mINFO
[39m - elasticsearch_js_test_runner - node - version[5.0.1-SNAPSHOT], pid[45808], build[9076512/2016-10-27T01:26:06.378Z], OS[Mac OS X/10.11.1/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_65/25.65-b01]
[33mWARN
[39m - elasticsearch_js_test_runner - node - version [5.0.1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
[32mINFO
[39m - elasticsearch_js_test_runner - plugins_service - loaded module [aggs-matrix-stats]
[32mINFO
[39m - elasticsearch_js_test_runner - plugins_service - loaded module [ingest-common]
[32mINFO
[39m - elasticsearch_js_test_runner - plugins_service - loaded module [lang-expression]
[32mINFO
[39m - elasticsearch_js_test_runner - plugins_service - loaded module [lang-groovy]
[32mINFO
[39m - elasticsearch_js_test_runner - plugins_service - loaded module [lang-mustache]
[32mINFO
[39m - elasticsearch_js_test_runner - plugins_service - loaded module [lang-painless]
[32mINFO
[39m - elasticsearch_js_test_runner - plugins_service - loaded module [percolator]
[32mINFO
[39m - elasticsearch_js_test_runner - plugins_service - loaded module [reindex]
[32mINFO
[39m - elasticsearch_js_test_runner - plugins_service - loaded module [transport-netty3]
[32mINFO
[39m - elasticsearch_js_test_runner - plugins_service - loaded module [transport-netty4]
[32mINFO
[39m - elasticsearch_js_test_runner - plugins_service - no plugins loaded
[32mINFO
[39m - elasticsearch_js_test_runner - node - initialized
[32mINFO
[39m - elasticsearch_js_test_runner - node - starting ...
[32mINFO
[39m - elasticsearch_js_test_runner - transport_service - publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
[32mINFO
[39m - elasticsearch_js_test_runner - cluster_service - new_master {elasticsearch_js_test_runner}{ivFq7IRzQI-drjQDAZufXA}{aTJlfKiPSwaWWepe7GtdVg}{127.0.0.1}{127.0.0.1:9300}{testattr=test}, reason: zen-disco-elected-as-master ([0] nodes joined)
[32mINFO
[39m - elasticsearch_js_test_runner - http_server - publish_address {127.0.0.1:9400}, bound_addresses {127.0.0.1:9400}
[32mINFO
[39m - elasticsearch_js_test_runner - node - started
[32mINFO
[39m - elasticsearch_js_test_runner - gateway_service - recovered [0] indices into cluster_state
[32m>> 
[39mStarted 1 Elasticsearch nodes.
 port 
 branch                         
 node name                    
 9400 
 5.0@9076512 (built 7 days ago) 
 elasticsearch_js_test_runner 
[4mRunning "mocha_integration:5.0" (mocha_integration) task
[24m
[4mRunning "mochacov:integration" (mochacov) task
[24m
  branch: 5.0
  port: 9400
  api version: 5.0
/Users/u/d/elasticsearch-js/node_modules/expect.js/index.js:102
      throw err;
      ^
Error: expected 'YamlDoc#version' to be a function
    at Assertion.assert (/Users/u/d/elasticsearch-js/node_modules/expect.js/index.js:96:13)
    at Assertion.a.Assertion.an (/Users/u/d/elasticsearch-js/node_modules/expect.js/index.js:268:12)
    at Function.a (/Users/u/d/elasticsearch-js/node_modules/expect.js/index.js:499:17)
    at /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_doc.js:124:54
    at arrayMap (/Users/u/d/elasticsearch-js/node_modules/lodash/lodash.js:653:23)
    at Function.map (/Users/u/d/elasticsearch-js/node_modules/lodash/lodash.js:9533:14)
    at Object.YamlDoc (/Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_doc.js:117:21)
    at /Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_file.js:22:13
    at arrayMap (/Users/u/d/elasticsearch-js/node_modules/lodash/lodash.js:653:23)
    at Object.map (/Users/u/d/elasticsearch-js/node_modules/lodash/lodash.js:9533:14)
    at Suite.<anonymous> (/Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_file.js:21:19)
    at context.describe.context.context (/Users/u/d/elasticsearch-js/node_modules/grunt-mocha-cov/node_modules/mocha/lib/interfaces/bdd.js:49:10)
    at new YamlFile (/Users/u/d/elasticsearch-js/test/integration/yaml_suite/yaml_file.js:20:3)
    at /Users/u/d/elasticsearch-js/test/integration/yaml_suite/run.js:36:14
    at /Users/u/d/elasticsearch-js/node_modules/lodash/lodash.js:3552:27
    at /Users/u/d/elasticsearch-js/node_modules/lodash/lodash.js:4938:15
    at baseForOwn (/Users/u/d/elasticsearch-js/node_modules/lodash/lodash.js:2988:24)
    at /Users/u/d/elasticsearch-js/node_modules/lodash/lodash.js:4907:18
    at baseMap (/Users/u/d/elasticsearch-js/node_modules/lodash/lodash.js:3551:7)
    at Object.map (/Users/u/d/elasticsearch-js/node_modules/lodash/lodash.js:9533:14)
    at Suite.<anonymous> (/Users/u/d/elasticsearch-js/test/integration/yaml_suite/run.js:35:19)
    at context.describe.context.context (/Users/u/d/elasticsearch-js/node_modules/grunt-mocha-cov/node_modules/mocha/lib/interfaces/bdd.js:49:10)
    at module.exports (/Users/u/d/elasticsearch-js/test/integration/yaml_suite/run.js:21:3)
    at Object.<anonymous> (/Users/u/d/elasticsearch-js/test/integration/yaml_suite/index_5_0.js:1:79)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/u/d/elasticsearch-js/node_modules/grunt-mocha-cov/node_modules/mocha/lib/mocha.js:187:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/u/d/elasticsearch-js/node_modules/grunt-mocha-cov/node_modules/mocha/lib/mocha.js:184:14)
    at Mocha.run (/Users/u/d/elasticsearch-js/node_modules/grunt-mocha-cov/node_modules/mocha/lib/mocha.js:405:31)
    at Object.<anonymous> (/Users/u/d/elasticsearch-js/node_modules/grunt-mocha-cov/node_modules/mocha/bin/_mocha:405:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
[33mWarning: 
 Use --force to continue.
[39m
[31mAborted due to warnings.
[39m
npm ERR! Test failed.  See above for more details.
```

Thanks,

Regards,
Sven

**Comment by spalger** [comment]
I have a feeling it is related to this https://github.com/elastic/elasticsearch/pull/21240#event-844742592

**Comment by xtuc** [comment]
You mean that the feature is not supported and that I need to skip this test ?

Your answer doesn't help me much.

Why should I skip this test ? Does the test suite succeed on your side ?

**Comment by spalger** [comment]
Sorry, my response wasn't meant to be an answer.

I haven't had time to look too deeply into this, but I'm thinking that I'll need to update the [`YamlDoc`](https://github.com/elastic/elasticsearch-js/blob/master/test/integration/yaml_suite/yaml_doc.js) class to conform to the new "version" skip clause defined in the linked Elasticsearch issue

**Comment by delvedor** [comment]
I'm working on this in https://github.com/elastic/elasticsearch-js/tree/refactor-test-suite :)
