### ISSUE TITLE
an id must be provided if version type or value are set;

### ISSUE THREAD

**Issue by ehsan-bay** [elastic/elasticsearch-js#464]
hi there, 
I am new in elastalert. I got this error after making my first alert. anybody can help? 

```
ERROR:root:Error writing alert info to Elasticsearch: TransportError(400, u'action_request_validation_exception', u'Validation Failed: 1: an id must be provided if version type or value are set;')
Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 1018, in writeback
    doc_type=doc_type, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 248, in create
    return self.index(index, doc_type, body, id=id, params=params, op_type='create')
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 84, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 113, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'action_request_validation_exception', u'Validation Failed: 1: an id must be provided if version type or value are set;')
INFO:elastalert:Ran Example rule from 2016-11-06 11:32 IRST to 2016-11-06 11:47 IRST: 0 query hits, 0 matches, 0 alerts sen
```

and this is my example_frequency.yaml file :

```yaml
es_host: localhost


# (Optional)
# Elasticsearch port
es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
es_username: *****
es_password: *****

# (Required)
# Rule name, must be unique
name: Example rule

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: metricbeat-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 50

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  hours: 1
filter:
- term:
    #some_field: "some_value"
    host: 'something'
    #count: 1


# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
- '*****@yahoo.com'
```

**Comment by spalger** [comment]
Hey @ehsan-bay, this repository is for the elasticsearch javascript client which is separate from elastalert.

Please [file an issue](https://github.com/Yelp/elastalert/issues/new) at the the elastalert repo: https://github.com/Yelp/elastalert

**Comment by ehsan-bay** [comment]
hi Spencer,
Thanks a lot.
