### ISSUE TITLE
Get EADDRNOTAVAIL after creating ~16.000 docs

### ISSUE THREAD

**Issue by Nomeasmo** [elastic/elasticsearch-js#54]
I've no clue whats wrong here. I played around with some options but didn't succeed.

``` js
client = new elasticsearch.Client({
    host: 'localhost:9200',
    agent: true,
    maxSockets: 5,
    connectionClass: "http",
    keepAlive: false
    // ,log: 'trace'
});
```

Working in OSX, node 0.10.25, es 1.0.1 

```
Elasticsearch ERROR: 2014-02-26T16:03:58Z
  Error: Request error, retrying -- connect EADDRNOTAVAIL
      at Log.error (/Users/oliver/Documents/node/splimporter/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/Users/oliver/Documents/node/splimporter/node_modules/elasticsearch/src/lib/transport.js:185:18)
      at HttpConnector.<anonymous> (/Users/oliver/Documents/node/splimporter/node_modules/elasticsearch/src/lib/connectors/http.js:138:7)
      at ClientRequest.bound (/Users/oliver/Documents/node/splimporter/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:52:17)
      at ClientRequest.EventEmitter.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1547:9)
      at Socket.EventEmitter.emit (events.js:95:17)
      at net.js:441:14
      at process._tickCallback (node.js:415:13)
```

**Comment by philberg** [comment]
@spalger I am facing the exact same issue running OSX 10.10.2 , node v0.12.7, and ES 1.6.0

I am able to replicate the issue using the sample code from @Nomeasmo above.  Could this issue needs to be resolved differently in 0.12 given the different http pooling?
