### ISSUE TITLE
parseError with elasticsearh-js 13.0.1

### ISSUE THREAD

**Issue by Lakshmihm** [elastic/elasticsearch-js#546]
We are using elasticsearch 2.4.0. We started facing memory issues with elasticsearch-js client version 12.1. We saw some known issues related to memory and we switched to elasticsearch -js issues 13.0.1 

After switching we are getting this exception for search calls

Elasticsearch ERROR: 2017-05-17T12:19:21Z
  Error: Request error, retrying
  POST http://elasticsearch:9200/products/product/_search?q=id%3A2672789668 => Parse Error
      at Log.error (/home/app/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/home/app/node_modules/elasticsearch/src/lib/transport.js:246:18)
      at HttpConnector.<anonymous> (/home/app/node_modules/elasticsearch/src/lib/connectors/http.js:157:7)
      at ClientRequest.bound (/home/app/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
      at emitOne (events.js:101:20)

Not sure what this exception exactly means. Is it because of incompatible versions ( is 2.4.0 not compatible with 13.0.1)?

Response much appreciated. Thanks

**Comment by spalger** [comment]
@Lakshmihm That `Parse Error` is coming from node.js, which means that node is unable to communicate with Elasticsearch for some reason.

Can you please verify that you can connect to elasticsearch from that machine using `curl`? Does this happen every time you use the search API? Are you using any other API methods?

**Comment by Lakshmihm** [comment]
@spalger thanks for the response. We have deployed elastic search deployed on kubernetes and we did have some network issues with KOPS. I will test with the fixed version and get back

On the other hand, the parseError is misleading. Would be good if the exception stack trace is more specific.

**Comment by Lakshmihm** [comment]
Hi,
I verified with the stable version of KOPS with elastic search deployed on kubernetes. 

Unfortunately the issue still persists. Connectivity with elastic search is fine.  version 12.1 doesn't throw this error but has memory issue

Any pointers on this is much appreciated. Thanks.

**Comment by spalger** [comment]
Starting in version 13.0 we began sending the `Content-Type` header with all requests. It's possible that this is causing issues with a proxy or some other component in the system. Can you try enabling trace logging and see if that gives any helpful information? Just add `log: 'trace'` to the client options.

**Comment by hashika2** [comment]
I have same issue when inserting logs to elasticsearch

`Parse Error: Expected HTTP/`

**Comment by delvedor** [comment]
Hello @hashika2, the legacy client is no longer maintained, I strongly recommend migrating to the new one!
Take a look [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/breaking-changes.html) to understand what's changed.
