### ISSUE TITLE
No Promise implementation found. In order for elasticsearch-js to create promises either specify the `defer` configuration or include a global Promise shim

### ISSUE THREAD

**Issue by SongJieCN** [elastic/elasticsearch-js#585]
Hi guys,

I got a error message from nodejs response. Where i want to do client.search from elasticsearch.

Error: No Promise implementation found. In order for elasticsearch-js to create promises either specify the `defer` configuration or include a global Promise shim
    at Transport.defer (/opt/news/node_modules/elasticsearch/src/lib/transport.js:116:11)
    at Object.action (/opt/news/node_modules/elasticsearch/src/lib/client_action.js:66:36)
    at module.exports (/opt/news/routes/index.js:28:12)
    at Layer.handle [as handle_request] (/opt/news/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/news/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/opt/news/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/news/node_modules/express/lib/router/layer.js:95:5)
    at /opt/news/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/opt/news/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/news/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/opt/news/node_modules/express/lib/router/index.js:176:3)
    at router (/opt/news/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/opt/news/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/news/node_modules/express/lib/router/index.js:312:13)

Anybody met this issue?

**Comment by SongJieCN** [comment]
OK, find the configuration.

var Bluebird = require('bluebird');
var client = new elasticsearch.Client({
  defer: function () {
    return Bluebird.defer();
  }
});
