### ISSUE TITLE
Can't .cat.indices() with browser build

### ISSUE THREAD

**Issue by ElMatella** [elastic/elasticsearch-js#586]
Hi, I am using the browser build version in order to make it work in browser. However, I have some problems listing the indices as the body of the response can not be parsed.

```
es.cat.indices({
  format: 'json'
}).then(response => {
  console.log(response)
})
```
```
{
  Serialization: {
    message: "Unable to parse/serialize body",
      body: "yellow open orders sEYO9XYnR96T25768yJsXA 5 1 158745 9142 415.6mb 415.6mb↵",
      status: 200,
      stack: "Error: Unable to parse/serialize body↵    at respo…s/elasticsearch-browser/elasticsearch.js:16680:8)"
  },
  body: "yellow open orders sEYO9XYnR96T25768yJsXA 5 1 158745 9142 415.6mb 415.6mb↵",
  message: "Unable to parse/serialize body",
  status: 200,
  stack: "Error: Unable to parse/serialize body↵    at respond (/home/john/Code/elastic-project/node_modules/elasticsearch-browser/elasticsearch.js:476:18)↵    at checkRespForFailure (/home/john/Code/elastic-project/node_modules/elasticsearch-browser/elasticsearch.js:459:8)↵    at XMLHttpRequest.xhr.onreadystatechange (/home/john/Code/elastic-project/node_modules/elasticsearch-browser/elasticsearch.js:16680:8)"
}

```

Same code works well on node

**Comment by ElMatella** [comment]
Ho, anyway, I just had to add the `v` option to true:

```
es.cat.indices({
  format: 'json',
  v: true
}).then(response => {
  console.log(response)
})
```
