### ISSUE TITLE
updateByQuery No feature for name [/main/document/_update_by_query?q=

### ISSUE THREAD

**Issue by kauegimenes** [elastic/elasticsearch-js#587]
```
client.updateByQuery({
  index: 'main',
  type: 'document',
  q: 'name:"bob"',
  body: {
      otherName: 'test'
  }
}, function (error, response) {
  if(error) return console.error(error);
});
```

**Comment by tsouza** [comment]
Can you please provide more info? What are the Elasticsearch and client versions?

**Comment by kauegimenes** [comment]
elasticsearch-js `13.3.1`
elasticsearch server `5.5.2 `

**Comment by tsouza** [comment]
I am failing to reproduce the issue. I actually get another error:
```javascript
client.updateByQuery(
  { index: "main", type:"document", q: 'name:"bob"', body: { otherName: "test" }  }, 
  (err, q) => console.log(err))
```
```
{ Error: [parsing_exception] Unknown key for a VALUE_STRING in [otherName]., with { line=1 & col=14 }
    at respond (/Users/thiago/node_modules/elasticsearch/src/lib/transport.js:307:15)
    at checkRespForFailure (/Users/thiago/node_modules/elasticsearch/src/lib/transport.js:266:7)
    at HttpConnector.<anonymous> (/Users/thiago/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/Users/thiago/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  status: 400,
  displayName: 'BadRequest',
  message: '[parsing_exception] Unknown key for a VALUE_STRING in [otherName]., with { line=1 & col=14 }',
  path: '/main/document/_update_by_query',
  query: { q: 'name:"bob"' },
  body: '{"otherName":"test"}',
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [otherName].","line":1,"col":14}],"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [otherName].","line":1,"col":14},"status":400}',
  toString: [Function],
  toJSON: [Function] }
```

Which is actually the expected error since the Update By Query API does not expects a body like:
```json 
{ "otherName": "test"  }
```

Are you sure it's version `5.5.2`? Also, is there a proxy in front of Elasticsearch?
