### ISSUE TITLE
working on a login page(authentication)  : promise is not a constructor

### ISSUE THREAD

**Issue by fagbolaoluwagbenga** [elastic/elasticsearch-js#608]
TypeError: promise is not a constructor
    at AuthProvider.webpackJsonp.208.AuthProvider.login (http://localhost:8100/build/main.js:85:23)
    at LoginPage.webpackJsonp.329.LoginPage.signin (http://localhost:8100/build/2.js:80:26)
    at Object.eval [as handleEvent] (ng:///LoginPageModule/LoginPage.ngfactory.js:103:31)
    at handleEvent (http://localhost:8100/build/vendor.js:13607:172)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15092:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/vendor.js:14679:12)
    at dispatchEvent (http://localhost:8100/build/vendor.js:10056:25)
    at http://localhost:8100/build/vendor.js:10670:38
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/vendor.js:36545:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)

**Comment by delvedor** [comment]
Hi! I'm closing this due to inactivity, if it is still an issue, please feel free to reopen! :)
