### ISSUE TITLE
Unable to revive connection but curl works fine

### ISSUE THREAD

**Issue by smietanka** [elastic/elasticsearch-js#615]
Hello I have problem with ElasticSearch build for browser. 
I've tried 3 ways to connect to my ES.
1. Node - works fine ( https://goo.gl/gULtiR )
2. CURL - works fine ( https://goo.gl/86Ky7W )
3. ElasticSearch JS - not working ( https://goo.gl/P1U94N )

On error i've this:
`"No Living connections"`
and
`"Error: No Living connections
    at d (https://localhost:44301/Scripts/elasticsearch/elasticsearch.jquery.min.js:7:5660)
    at e (https://localhost:44301/Scripts/elasticsearch/elasticsearch.jquery.min.js:10:18895)
    at i.run (https://localhost:44301/Scripts/elasticsearch/elasticsearch.jquery.min.js:7:1663)
    at h (https://localhost:44301/Scripts/elasticsearch/elasticsearch.jquery.min.js:7:1167)"`

II tried add .js minified and not minified and with both files error is exactly same.
There is any solution ?

**Comment by smietanka** [comment]
In non minified .js I have this stack: 
`"Error: No Living connections
    at sendReqWithConnection (https://localhost:44301/Scripts/elasticsearch/elasticsearch.jquery.js:627:16)
    at next (https://localhost:44301/Scripts/elasticsearch/elasticsearch.jquery.js:16408:8)
    at Item.run (https://localhost:44301/Scripts/elasticsearch/elasticsearch.jquery.js:234:15)
    at drainQueue (https://localhost:44301/Scripts/elasticsearch/elasticsearch.jquery.js:204:43)"`

**Comment by spalger** [comment]
What errors are you getting in the browser console?

**Comment by delvedor** [comment]
Hi! I'm closing this due to inactivity, if it is still an issue, please feel free to reopen! :)
