### ISSUE TITLE
Returns Undefined when used inside a docker container

### ISSUE THREAD

**Issue by gsaxam** [elastic/elasticsearch-js#623]
I am running a nodeJS app with elasticsearch-js plugin inside a docker container and I receive this error:

```
/usr/src/app/routes/index.js:548
        response.hits.hits.forEach(function (hit) {
                     ^

TypeError: Cannot read property 'hits' of undefined
    at getMoreUntilDone (/usr/src/app/routes/index.js:548:22)
    at respond (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:326:9)
    at checkRespForFailure (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:266:7)
    at HttpConnector.<anonymous> (/usr/src/app/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/usr/src/app/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Linux 2.6.32-696.10.2.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! elastic@1.0.10 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elastic@1.0.10 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the elasticview package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs elastic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls elastic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

**Comment by osukaa** [comment]
Did you check the callback error to see if it contained any error?

**Comment by gsaxam** [comment]
Yeah. This is the error.
```
Elasticsearch ERROR: 2018-01-19T21:05:01Z
  Error: Request error, retrying
  POST <ES_HOST_HERE>/es_search/_search/scroll?scroll=5m => read ECONNRESET
      at Log.error (/usr/src/app/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:258:18)
      at HttpConnector.<anonymous> (/usr/src/app/node_modules/elasticsearch/src/lib/connectors/http.js:157:7)
      at ClientRequest.bound (/usr/src/app/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
      at emitOne (events.js:115:13)
      at ClientRequest.emit (events.js:210:7)
      at TLSSocket.socketErrorListener (_http_client.js:401:9)
      at emitOne (events.js:115:13)
      at TLSSocket.emit (events.js:210:7)
      at emitErrorNT (internal/streams/destroy.js:64:8)
{ Error: No Living connections
    at sendReqWithConnection (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:225:15)
    at next (/usr/src/app/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'No Living connections' }
```
