### ISSUE TITLE
this.log.info is not a function

### ISSUE THREAD

**Issue by Overdrivr** [elastic/elasticsearch-js#631]
The client crashes on initialization if the config object comes from the [`config`](https://www.npmjs.com/package/config) library, and option 'log' is used.

Repro

```
./
test.js
config/
   default.json
```

> test.js
```
'use strict';

var elasticsearch = require('elasticsearch');
var config = require('config');
var creds = config.get('db.elasticsearch.credentials');

module.exports.client = new elasticsearch.Client(creds);
```

> ./config/default.json
```
{
  "db": {
    "elasticsearch": {
      "credentials": {
        "host": "elasticsearch:9200",
        "log": "trace",
        "httpAuth": "elastic:changeme"
      }
    }
  }
}
```

```
$ node
> require('./test');
```
```
TypeError: this.log.info is not a function
    at ConnectionPool.addConnection (C:\Users\xxx\Gitlab\****\node_modules\elasticsearch\src\lib\connection_pool.js:276:14)
    at ConnectionPool.setHosts (C:\Users\xxx\Gitlab\****\node_modules\elasticsearch\src\lib\connection_pool.js:321:12)
    at Transport.setHosts (C:\Users\xxx\Gitlab\****\node_modules\elasticsearch\src\lib\transport.js:450:23)
    at new Transport (C:\Users\xxx\Gitlab\****\node_modules\elasticsearch\src\lib\transport.js:67:10)
    at new EsApiClient (C:\Users\xxx\Gitlab\****\node_modules\elasticsearch\src\lib\client.js:57:22)
    at new Client (C:\Users\xxx\Gitlab\****\node_modules\elasticsearch\src\lib\client.js:101:10)
```

It probably comes from a conflict between the `config` module and `elasticsearch` way of parsing the `log` key of the config object.

**Comment by LucasLeandro1204** [comment]
Same problem here.

**Comment by mike-zenith** [comment]
I also encountered the same issue and this fixed it:
```
const client = new elasticsearch.Client({ 
    ... config.get('... elasticsearch'), 
    log: config.get('....elasticsearch.log') 
});
```
I guess it has something to do with object references.

**Comment by jjasonclark** [comment]
I'm also encountering the error. As @mike-zenith points out you can just set the `log` property to mitigate the issue. Although I found that you can force the result to be a plain Object type.

```
'use strict';

const config = require('config');
const elasticsearch = require('elasticsearch');

const elasticsearchClient = new elasticsearch.Client(
  // Force Object type from the Node-Config return
  // See https://github.com/elastic/elasticsearch-js/issues/631
  config.util.toObject('elasticsearch')
);

module.exports = { elasticsearchClient };
```

This might have something to do with an immutable return type from Node-Config.
