### ISSUE TITLE
application/x-ldjson is not supported error on msearch

### ISSUE THREAD

**Issue by unagi2020** [elastic/elasticsearch-js#641]
I have been trying to get following code to work on 14.0.1 connecting to 6.2.2
```
client.msearch({
  body: [
    {},
    { query: { match_all: {} } },
  ]
});
```
No matter what I do I end up getting the following error. The above the syntax works great with 13.3.1 connecting to 5.5.2
```
{ Error: Content-Type header [application/x-ldjson] is not supported
    at respond (/home/app/node_modules/hapi-elastic/node_modules/elasticsearch/src/lib/transport.js:289:15)
    at checkRespForFailure (/home/app/node_modules/hapi-elastic/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/home/app/node_modules/hapi-elastic/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/home/app/node_modules/hapi-elastic/node_modules/lodash/index.js:3095:19)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:439:23)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
  status: 406,
  displayName: 'NotAcceptable',
  message: 'Content-Type header [application/x-ldjson] is not supported',
  body: 
   { error: 'Content-Type header [application/x-ldjson] is not supported',
     status: 406 } }
```
What can i do to circumvent the error ? Would hate to go back to previous verison.

**Comment by unagi2020** [comment]
My bad. One of the npms was still using old version. Closing this issue as version upgrading in npm resolved the issue.
