### ISSUE TITLE
Error: Request error, retrying, No living connections

### ISSUE THREAD

**Issue by GZWZC** [elastic/elasticsearch-js#654]
helo,i meet a problem that i fail to run the project.
in my Terminal, i run the `node server.js` command, and then the system is killed the process。
how should i do that npm the server?

server.js

    var elasticsearch = require('elasticsearch'); 
    var esclient = new elasticsearch.Client({ 	
        host: 'localhost:9200', 	
        log: 'trace' 
    }); 
    esclient.ping({ 	
        // ping usually has a 3000ms timeout 	
        requestTimeout: 1000 
    }, function (error) { 	
        if (error) { 		
            console.trace('elasticsearch cluster is down!'); 	
        } else { 		
            console.log('All is well'); 	
        } 
    });

bash-3.2# node server.js 

    Elasticsearch INFO: 2018-04-25T12:45:12Z
      Adding connection to http://localhost:9200/
    
    { [Function: action]
      spec: 
       { url: { fmt: '/' },
         requestTimeout: 3000,
         method: 'HEAD',
         params: { filterPath: [Object] } } }
    Elasticsearch DEBUG: 2018-04-25T12:45:12Z
      starting request {
        "method": "HEAD",
        "requestTimeout": 3000,
        "castExists": true,
        "path": "/",
        "query": {}
      }
      
    
    Elasticsearch TRACE: 2018-04-25T12:45:12Z
      -> HEAD http://localhost:9200/
      
      <- 0
      
    
    Elasticsearch ERROR: 2018-04-25T12:45:12Z
      Error: Request error, retrying
      HEAD http://localhost:9200/ => connect ECONNREFUSED 127.0.0.1:9200
          at Log.error (/Users/zhichaowang/testEs/node_modules/_elasticsearch@14.2.2@elasticsearch/src/lib/log.js:225:56)
          at checkRespForFailure (/Users/zhichaowang/testEs/node_modules/_elasticsearch@14.2.2@elasticsearch/src/lib/transport.js:258:18)
          at HttpConnector.<anonymous> (/Users/zhichaowang/testEs/node_modules/_elasticsearch@14.2.2@elasticsearch/src/lib/connectors/http.js:157:7)
          at ClientRequest.bound (/Users/zhichaowang/testEs/node_modules/_lodash@2.4.2@lodash/dist/lodash.js:729:21)
          at emitOne (events.js:116:13)
          at ClientRequest.emit (events.js:211:7)
          at Socket.socketErrorListener (_http_client.js:387:9)
          at emitOne (events.js:116:13)
          at Socket.emit (events.js:211:7)
          at emitErrorNT (internal/streams/destroy.js:64:8)
    
    Elasticsearch TRACE: 2018-04-25T12:45:12Z
      -> HEAD http://localhost:9200/
      
      <- 0
      
    
    Elasticsearch WARNING: 2018-04-25T12:45:12Z
      Unable to revive connection: http://localhost:9200/
    
    Elasticsearch WARNING: 2018-04-25T12:45:12Z
      No living connections
    
    Trace: elasticsearch cluster is down!
        at /Users/zhichaowang/testEs/server.js:9:11
        at respond (/Users/zhichaowang/testEs/node_modules/_elasticsearch@14.2.2@elasticsearch/src/lib/transport.js:326:9)
        at sendReqWithConnection (/Users/zhichaowang/testEs/node_modules/_elasticsearch@14.2.2@elasticsearch/src/lib/transport.js:225:7)
        at next (/Users/zhichaowang/testEs/node_modules/_elasticsearch@14.2.2@elasticsearch/src/lib/connection_pool.js:213:7)
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickCallback (internal/process/next_tick.js:180:9)
    Elasticsearch TRACE: 2018-04-25T12:46:37Z
      -> HEAD http://localhost:9200/
      
      <- 0
      
    
    Elasticsearch TRACE: 2018-04-25T12:48:37Z
      -> HEAD http://localhost:9200/
      
      <- 0
      
    
    Elasticsearch TRACE: 2018-04-25T12:51:27Z
      -> HEAD http://localhost:9200/
      
      <- 0
      
    
    Elasticsearch TRACE: 2018-04-25T12:55:27Z
      -> HEAD http://localhost:9200/
      
      <- 0

**Comment by GZWZC** [comment]
i am sorry.
because i'm not run the esDb,
