### ISSUE TITLE
Unable to revive connection: http://localhost:9200/

### ISSUE THREAD

**Issue by ajayrfhp** [elastic/elasticsearch-js#69]
I am using v0.10.25 still getting this .It was working fine 2 days ago .

``` sh
Elasticsearch ERROR: 2014-03-19T08:05:18Z
  Error: Request error, retrying -- connect ECONNREFUSED
      at Log.error (/home/ajay/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/home/ajay/node_modules/elasticsearch/src/lib/transport.js:185:18)
      at HttpConnector.<anonymous> (/home/ajay/node_modules/elasticsearch/src/lib/connectors/http.js:150:7)
      at ClientRequest.bound (/home/ajay/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)
      at ClientRequest.EventEmitter.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1547:9)
      at Socket.EventEmitter.emit (events.js:95:17)
      at net.js:441:14
      at process._tickCallback (node.js:415:13)

Elasticsearch WARNING: 2014-03-19T08:05:18Z
  Unable to revive connection: http://127.0.0.1:9200/

Elasticsearch WARNING: 2014-03-19T08:05:18Z
  No living connections

{ message: 'No Living connections' }
elasticsearch cluster is down!
```

**Comment by hellboy81** [comment]
äh... If I should write integration tests, how can I mock Elastic search?

**Comment by hellboy81** [comment]
`sinon` `stubs` are only for unit tests

**Comment by matt212** [comment]
https://github.com/RaananW/express.js-elasticsearch-autocomplete-demo/issues/2

**Comment by MajidD4t1qbit** [comment]
On OSX with ElasticSearch server running in a docker container, I was getting the `ECONNREFUSED ` error. I had mapped 9200 of the container to 9200 of the localhost and was trying to get to ElasticSearch through `localhost:9200`.

Just had to change the elastic search's ip in my JS code directly to `docker-machine`'s ip which you can get using ```echo $(docker-machine ip)``` and it started working. Strange, but might solve someone's problem if just wanna get it to work. 

I'm using ` "elasticsearch": "11.0.1" `

**Comment by jaystark** [comment]
I am using the plastic search https://github.com/sleimanx2/plastic However while running I am getting an error like as follow
`[2016-08-09 10:00:22] log.WARNING: Curl exception encountered. [] []
[2016-08-09 10:00:22] log.WARNING: Request Failure: {"method":"GET","uri":"http://127.0.0.1:9200/plastic/books/_search","headers":{"host":["127.0.0.1:9200"]},"HTTP code":null,"duration":0.202,"error":"cURL error 7: Failed to connect to 127.0.0.1 port 9200: Connection refused"} []
[2016-08-09 10:00:22] log.WARNING: Response [null] []
[2016-08-09 10:00:22] log.WARNING: Marking node 127.0.0.1:9200 dead. [] []
[2016-08-09 10:00:22] log.WARNING: Retries left? true [] []
[2016-08-09 10:00:22] log.CRITICAL: No alive nodes found in cluster [] []`

Please suggest me any way to resolve this....Thanks in advance

**Comment by john20xdoe** [comment]
@MajidD4t1qbit  where did you put the `echo $(docker-machine ip) `line? in your app?

**Comment by slfk** [comment]
Please help coming below error during elk setup in docker-compose kibana           | {"type":"log","@timestamp":"2019-08-11T23:19:38Z","tags":["status","plugin:visualizations@7.3.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana           | {"type":"log","@timestamp":"2019-08-11T23:19:39Z","tags":["error","elasticsearch","admin"],"pid":1,"message":"Request error, retrying\nGET http://elasticsearch:9200/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip => connect ECONNREFUSED 172.20.0.2:9200"}
kibana           | {"type":"log","@timestamp":"2019-08-11T23:19:39Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana           | {"type":"log","@timestamp":"2019-08-11T23:19:39Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana           | {"type":"log","@timestamp":"2019-08-11T23:19:39Z","tags":["status","plugin:xpack_main@7.3.0","error"],"pid":1,"state":"red","message":"Status changed from
