### ISSUE TITLE
When using async/await promise reject is not handled as expected

### ISSUE THREAD

**Issue by rwlaschin** [elastic/elasticsearch-js#789]
## 🐛 Bug Report

When not including required parameters in the client.delete function.  The async version reports 'callback is not a function' instead of an appropriate error message concerning the missing 'id' parameter.

## To Reproduce

Paste your code here:

```js
const { Client, errors } = require('@elastic/elasticsearch');
const client = new Client({ "node": "http://localhost:9200" });

async del(index) {
      try {
         await client.delete({ index });
      } catch (e) {
         console.error(e);
      }
}
del('article').then( (result) => {
   console.log('All good');
}).catch( (err) => {
     console.error('shoot', err);
})
```

## Expected behavior

Expected error message "ConfigurationError: Missing required parameter: id"

Paste the results here:

```js
{ ConfigurationError: Missing required parameter: id
    at _delete (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/node_modules/@elastic/elasticsearch/api/api/delete.js:86:9)
    at Client._lazyLoad [as delete] (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/node_modules/@elastic/elasticsearch/api/index.js:498:12)
    at Query._callee5$ (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/server/lib/controller/Search/index.js:105:32)
    at tryCatch (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/server/lib/controller/Search/index.js:3:590)
    at _next (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/server/lib/controller/Search/index.js:3:928)
    at /Users/rwlaschin/Work/Wholosophy/wholosophy-web/server/lib/controller/Search/index.js:3:1093
    at new Promise (<anonymous>) name: 'ConfigurationError' }
```

## Your Environment

- *node version*: v10.15.2
- *@elastic/elasticsearch version*: =6.6.2
- *os*: Mac

**Comment by delvedor** [comment]
Hello! Thank you for checking out the new client!
This bug has already been fixed in https://github.com/elastic/elasticsearch-js/commit/a90e9e1fe1eea3faf9be1b8eb48d4aa20dd72721, but it has not been released yet.
I'll release the first rc1 in the next days, stay tuned :)

**Comment by delvedor** [comment]
Side note: I just opened https://github.com/elastic/elasticsearch-js/pull/790 that improves the internal handling of rejections, and possibly reduces the overall size of the package.

**Comment by nicopenaredondo** [comment]
Hello. Is this already fixed ? I'm currently using @elastic/elasticsearch@7.9.1
