### ISSUE TITLE
How to use 'sort' using '_script when Searching something 

### ISSUE THREAD

**Issue by drake-jin** [elastic/elasticsearch-js#825]
I wanna use `_script` at `sort` like this [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-request-sort.html#_script_based_sorting) How can I get this?

It's my code

``` js
client.search({
        index: 'articles',
        type: 'article',
        size: 6,
        minScore: 0.9,
        query: {
          filtered: {
            query: {
              multi_match: {
                query: 'Bicycle',
                fields: ['title^2', 'content'],
                minimum_should_match: '100%',
              },
            },
            filter: {
              and: {
                filters: [
                  { term: { visible: true } },
                  { terms: { type: ['Foo', 'Bar'] } },
                  { terms: { publish_range: [1, 2, 3] } },
                ],
              },
            },
          },
        },
        sort: {
          _script: {
            type: 'number',
            script: {
              inline: 'pow((doc[\'create_at\'].value - new Date().getTime() / 1000) / 3600, 2) / 4000 * (20.0 / _score) - pow(_score * 1.0, 2)',
            },
            order: 'asc',
          },
        },
      }, (err, data) => {
        console.log(err)
        console.log(data)
        done()
      })
    })
``` 

but, It has occured an error 

```
TypeError: Invalid sort: expected be a comma separated list, array, number or string.
    at Object.list (/Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/2.3.1/node_modules/elasticsearch/src/lib/client_action.js:146:15)
    at exec (/Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/2.3.1/node_modules/elasticsearch/src/lib/client_action.js:327:65)
    at EsApiClient.action [as search] (/Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/2.3.1/node_modules/elasticsearch/src/lib/client_action.js:61:16)
    at Context.it (/Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/2.3.1/index.js:75:14)
    at callFnAsync (/Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/node_modules/mocha/lib/runnable.js:415:21)
    at Test.Runnable.run (/Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/node_modules/mocha/lib/runnable.js:357:7)
    at Runner.runTest (/Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/node_modules/mocha/lib/runner.js:535:10)
    at /Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/node_modules/mocha/lib/runner.js:653:12
    at next (/Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/node_modules/mocha/lib/runner.js:447:14)
    at /Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/node_modules/mocha/lib/runner.js:457:7
    at next (/Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/node_modules/mocha/lib/runner.js:362:14)
    at Immediate._onImmediate (/Users/drakejin/Desktop/Workspace/daangn/dockerfiles/elasticsearch/test/node_modules/mocha/lib/runner.js:425:5)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

hmmmmmmmmmmm... Where should I jot down that code?

**Comment by drake-jin** [comment]
Hmmm.. I got the answer myself. 

``` javascript
      client.search({
        index: 'articles-',
        type: 'article',
        size: 6,
        minScore: 0.9,
        body: {
          query: {
            filtered: {
              query: {
                multi_match: {
                  query: '자전거',
                  fields: ['title^2', 'content'],
                  minimum_should_match: '100%',
                },
              },
              filter: {
                and: {
                  filters: [
                    { term: { visible: true } },
                    { terms: { type: ['FleaMarketArticle', 'BusinessArticle'] } },
                    { terms: { publish_range: [1, 2, 3] } },
                  ],
                },
              },
            },
          },
          sort: {
            _script: {
              type: 'number',
              script: {
                inline: 'pow((doc[\'published_at_i\'].value - new Date().getTime() / 1000) / 3600, 2) / 4000 * (20.0 / _score) - pow(_score * 1.0, 2)',
              },
              order: 'asc',
            },
          },
        },
      }, (err, data) => {
        console.log(err)
        console.log(data.hits.hits)
        done()
      })
```

How can I get API documents more detailed one? 
not this [link](https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html). Understandably, I agree with the link can be a document for 'elastic/elasticsearch-js'. But, I think it's a little bit tough for Beginners.

If you guys have an API document I said, Would you let me know or write that on `README.md`?
Or, You have a plan to make a new one, I'll commit the work.
