### ISSUE TITLE
Original node connection discarded

### ISSUE THREAD

**Issue by Jtaks** [elastic/elasticsearch-js#923]
## 🐛 Bug Report
@elastic/elasticsearch overwrites my node connection after retrieving a list of node info containing ip addresses.

## To Reproduce

1. Install [helm/charts/stable/elasticsearch](https://github.com/helm/charts/tree/master/stable/elasticsearch) with no external IP addresses
2. Portforward into a node that can receive requests. Ex: `kubectl port-forward -n search elasticsearch-client-<pod-id> 9200`
3. Run the script below and observe the logs (around 15:52:47.798Z in output.log below)

```sh
> DEBUG=elasticsearch node main.js
```

*main.js*:

```js
// * "@elastic/elasticsearch": "^6.6.0",
const { Client } = require('@elastic/elasticsearch')

async function main () {
  const client = new Client({
    node: 'http://localhost:9200',
    agent: { keepAlive: true },
    requestTimeout: 1000 * 60,
    sniffOnStart: true,
    suggestCompression: true,
    compression: 'gzip'
  })

  console.log('Initialize')

  setTimeout(async () => {
    console.log('Trying to ping')
    await client.ping()
    console.log('Complete')
  }, 60000)
}

main()
```

output.logs:

```
2019-07-25T15:52:47.567Z elasticsearch Adding a new connection { url: 'http://localhost:9200/',
  id: 'http://localhost:9200/',
  headers: null,
  deadCount: 0,
  resurrectTimeout: 0,
  _openRequests: 0,
  status: 'alive',
  roles: { master: true, data: true, ingest: true, ml: false } }
2019-07-25T15:52:47.569Z elasticsearch Started sniffing request
2019-07-25T15:52:47.569Z elasticsearch Nothing to resurrect
2019-07-25T15:52:47.569Z elasticsearch qserialize undefined
2019-07-25T15:52:47.570Z elasticsearch Starting a new request { method: 'GET',
  path: '_nodes/_all/http',
  headers:
   { 'User-Agent':
      'elasticsearch-js/6.8.1 (linux 4.15.0-54-generic-x64; Node.js v10.16.0)',
     'Accept-Encoding': 'gzip,deflate' },
  querystring: '',
  timeout: 300000 }
2019-07-25T15:52:47.576Z elasticsearch Nothing to resurrect
2019-07-25T15:52:47.576Z elasticsearch qserialize {}
2019-07-25T15:52:47.576Z elasticsearch Starting a new request { method: 'HEAD',
  path: '/',
  body: null,
  querystring: '',
  headers:
   { 'User-Agent':
      'elasticsearch-js/6.8.1 (linux 4.15.0-54-generic-x64; Node.js v10.16.0)',
     'Accept-Encoding': 'gzip,deflate' },
  timeout: 300000 }
2019-07-25T15:52:47.790Z elasticsearch Marking as 'alive' connection 'http://localhost:9200/'
2019-07-25T15:52:47.796Z elasticsearch Deserializing {"_nodes":
  {"total":5,
    "successful":5,
    "failed":0},
  "cluster_name":"elasticsearch",
  "nodes":{
    "rOnowTW5RQ2kIp-Mj3_WjA":{"name":"elasticsearch-master-1",
      "transport_address":"xx.xx.x.xx:9300",
      "host":"xx.xx.x.xx",
      "ip":"xx.xx.x.xx",
      "version":"6.6.0",
      "build_flavor":"oss",
      "build_type":"tar",
      "build_hash":"a9861f4",
      "roles":["master","ingest"],
      "http":{"bound_address":["0.0.0.0:9200"],
        "publish_address":"xx.xx.x.xx:9200",
        "max_content_length_in_bytes":104857600}},
    "n-Pqc37oRYm8b_tbEdgZ5w":{"name":"elasticsearch-data-0",
      "transport_address":"xx.xx.x.x:9300",
      "host":"xx.xx.x.x",
      "ip":"xx.xx.x.x",
      "version":"6.6.0",
      "build_flavor":"oss",
      "build_type":"tar",
      "build_hash":"a9861f4",
      "roles":["data","ingest"],
      "http":{"bound_address":["0.0.0.0:9200"],
        "publish_address":"xx.xx.x.x:9200",
        "max_content_length_in_bytes":104857600}},
    "lI3jhn0xQiSZBSF6Y0pGeQ":{"name":"elasticsearch-master-2",
        "transport_address":"xx.xx.x.x:9300",
        "host":"xx.xx.x.x",
        "ip":"xx.xx.x.x",
        "version":"6.6.0",
        "build_flavor":"oss",
        "build_type":"tar",
        "build_hash":"a9861f4",
        "roles":["master","ingest"],
        "http":{"bound_address":["0.0.0.0:9200"],
          "publish_address":"xx.xx.x.x:9200",
          "max_content_length_in_bytes":104857600}},
      "5_kS6iqtRf-2wI7Yja7NnQ":{"name":"elasticsearch-client-d5444d968-6s9zz",
        "transport_address":"xx.xx.x.xx:9300",
        "host":"xx.xx.x.xx",
        "ip":"xx.xx.x.xx",
        "version":"6.8.1",
        "build_flavor":"oss",
        "build_type":"docker",
        "build_hash":"1fad4e1",
        "roles":["ingest"],
        "http":{"bound_address":["0.0.0.0:9200"],
          "publish_address":"xx.xx.x.xx:9200",
          "max_content_length_in_bytes":104857600}},
      "4aM2tEc4SnyZ9pYxBy9-uw":{"name":"elasticsearch-master-0",
        "transport_address":"xx.xx.x.x:9300",
        "host":"xx.xx.x.x",
        "ip":"xx.xx.x.x",
        "version":"6.6.0",
        "build_flavor":"oss",
        "build_type":"tar",
        "build_hash":"a9861f4",
        "roles":["master","ingest"],
        "http":{"bound_address":["0.0.0.0:9200"],
          "publish_address":"xx.xx.x.x:9200",
          "max_content_length_in_bytes":104857600}}}}
2019-07-25T15:52:47.796Z elasticsearch Marking as 'alive' connection 'http://localhost:9200/'
2019-07-25T15:52:47.796Z elasticsearch Sniffing ended successfully { _nodes: { total: 5, successful: 5, failed: 0 },
  cluster_name: 'elasticsearch',
  nodes:
   { 'rOnowTW5RQ2kIp-Mj3_WjA':
      { name: 'elasticsearch-master-1',
        transport_address: 'xx.xx.x.xx:9300',
        host: 'xx.xx.x.xx',
        ip: 'xx.xx.x.xx',
        version: '6.6.0',
        build_flavor: 'oss',
        build_type: 'tar',
        build_hash: 'a9861f4',
        roles: [Array],
        http: [Object] },
     'n-Pqc37oRYm8b_tbEdgZ5w':
      { name: 'elasticsearch-data-0',
        transport_address: 'xx.xx.x.x:9300',
        host: 'xx.xx.x.x',
        ip: 'xx.xx.x.x',
        version: '6.6.0',
        build_flavor: 'oss',
        build_type: 'tar',
        build_hash: 'a9861f4',
        roles: [Array],
        http: [Object] },
     lI3jhn0xQiSZBSF6Y0pGeQ:
      { name: 'elasticsearch-master-2',
        transport_address: 'xx.xx.x.x:9300',
        host: 'xx.xx.x.x',
        ip: 'xx.xx.x.x',
        version: '6.6.0',
        build_flavor: 'oss',
        build_type: 'tar',
        build_hash: 'a9861f4',
        roles: [Array],
        http: [Object] },
     '5_kS6iqtRf-2wI7Yja7NnQ':
      { name: 'elasticsearch-client-d5444d968-6s9zz',
        transport_address: 'xx.xx.x.xx:9300',
        host: 'xx.xx.x.xx',
        ip: 'xx.xx.x.xx',
        version: '6.8.1',
        build_flavor: 'oss',
        build_type: 'docker',
        build_hash: '1fad4e1',
        roles: [Array],
        http: [Object] },
     '4aM2tEc4SnyZ9pYxBy9-uw':
      { name: 'elasticsearch-master-0',
        transport_address: 'xx.xx.x.x:9300',
        host: 'xx.xx.x.x',
        ip: 'xx.xx.x.x',
        version: '6.6.0',
        build_flavor: 'oss',
        build_type: 'tar',
        build_hash: 'a9861f4',
        roles: [Array],
        http: [Object] } } }
2019-07-25T15:52:47.797Z elasticsearch Updating the connection pool
2019-07-25T15:52:47.798Z elasticsearch Adding a new connection { url: 'http://xx.xx.x.xx:9200/',
  id: 'rOnowTW5RQ2kIp-Mj3_WjA',
  headers: null,
  deadCount: 0,
  resurrectTimeout: 0,
  _openRequests: 0,
  status: 'alive',
  roles: { master: true, data: true, ingest: true, ml: false } }
2019-07-25T15:52:47.798Z elasticsearch Adding a new connection { url: 'http://xx.xx.x.x:9200/',
  id: 'n-Pqc37oRYm8b_tbEdgZ5w',
  headers: null,
  deadCount: 0,
  resurrectTimeout: 0,
  _openRequests: 0,
  status: 'alive',
  roles: { master: true, data: true, ingest: true, ml: false } }
2019-07-25T15:52:47.798Z elasticsearch Adding a new connection { url: 'http://xx.xx.x.x:9200/',
  id: 'lI3jhn0xQiSZBSF6Y0pGeQ',
  headers: null,
  deadCount: 0,
  resurrectTimeout: 0,
  _openRequests: 0,
  status: 'alive',
  roles: { master: true, data: true, ingest: true, ml: false } }
2019-07-25T15:52:47.798Z elasticsearch Adding a new connection { url: 'http://xx.xx.x.xx:9200/',
  id: '5_kS6iqtRf-2wI7Yja7NnQ',
  headers: null,
  deadCount: 0,
  resurrectTimeout: 0,
  _openRequests: 0,
  status: 'alive',
  roles: { master: true, data: true, ingest: true, ml: false } }
2019-07-25T15:52:47.798Z elasticsearch Adding a new connection { url: 'http://xx.xx.x.x:9200/',
  id: '4aM2tEc4SnyZ9pYxBy9-uw',
  headers: null,
  deadCount: 0,
  resurrectTimeout: 0,
  _openRequests: 0,
  status: 'alive',
  roles: { master: true, data: true, ingest: true, ml: false } }
2019-07-25T15:52:47.798Z elasticsearch Removing connection { url: 'http://localhost:9200/',
  id: 'http://localhost:9200/',
  headers: null,
  deadCount: 0,
  resurrectTimeout: 0,
  _openRequests: 0,
  status: 'alive',
  roles: { master: true, data: true, ingest: true, ml: false } }
2019-07-25T15:52:47.799Z elasticsearch Closing connection http://localhost:9200/
2019-07-25T15:53:32.803Z elasticsearch Nothing to resurrect
2019-07-25T15:53:32.804Z elasticsearch qserialize {}
2019-07-25T15:53:32.804Z elasticsearch Starting a new request { method: 'HEAD',
  path: '/',
  body: null,
  querystring: '',
  headers:
   { 'User-Agent':
      'elasticsearch-js/6.8.1 (linux 4.15.0-54-generic-x64; Node.js v10.16.0)',
     'Accept-Encoding': 'gzip,deflate' },
  timeout: 300000 }
2019-07-25T15:55:42.410Z elasticsearch Marking as 'dead' connection 'n-Pqc37oRYm8b_tbEdgZ5w'
2019-07-25T15:55:42.410Z elasticsearch Retrying request, there are still 2 attempts { method: 'HEAD',
  path: '/',
  body: null,
  querystring: '',
  headers:
   { 'User-Agent':
      'elasticsearch-js/6.8.1 (linux 4.15.0-54-generic-x64; Node.js v10.16.0)',
     'Accept-Encoding': 'gzip,deflate' },
  timeout: 300000 }
2019-07-25T15:55:42.410Z elasticsearch Nothing to resurrect
2019-07-25T15:55:42.410Z elasticsearch qserialize 
2019-07-25T15:55:42.410Z elasticsearch Starting a new request { method: 'HEAD',
  path: '/',
  body: null,
  querystring: '',
  headers:
   { 'User-Agent':
      'elasticsearch-js/6.8.1 (linux 4.15.0-54-generic-x64; Node.js v10.16.0)',
     'Accept-Encoding': 'gzip,deflate' },
  timeout: 300000 }
2019-07-25T15:57:53.481Z elasticsearch Marking as 'dead' connection '5_kS6iqtRf-2wI7Yja7NnQ'
2019-07-25T15:57:53.481Z elasticsearch Retrying request, there are still 1 attempts { method: 'HEAD',
  path: '/',
  body: null,
  querystring: '',
  headers:
   { 'User-Agent':
      'elasticsearch-js/6.8.1 (linux 4.15.0-54-generic-x64; Node.js v10.16.0)',
     'Accept-Encoding': 'gzip,deflate' },
  timeout: 300000 }
2019-07-25T15:57:53.482Z elasticsearch Starting a new request { method: 'HEAD', path: '/', timeout: 3000 }
2019-07-25T15:57:53.483Z elasticsearch qserialize 
2019-07-25T15:57:53.483Z elasticsearch Starting a new request { method: 'HEAD',
  path: '/',
  body: null,
  querystring: '',
  headers:
   { 'User-Agent':
      'elasticsearch-js/6.8.1 (linux 4.15.0-54-generic-x64; Node.js v10.16.0)',
     'Accept-Encoding': 'gzip,deflate' },
  timeout: 300000 }
2019-07-25T15:57:56.487Z elasticsearch Resurrect: connection 'n-Pqc37oRYm8b_tbEdgZ5w' is still dead
2019-07-25T15:57:56.487Z elasticsearch Marking as 'dead' connection 'n-Pqc37oRYm8b_tbEdgZ5w'
2019-07-25T15:57:56.488Z elasticsearch Request aborted { method: 'HEAD', path: '/', timeout: 3000 }
2019-07-25T16:00:04.553Z elasticsearch Marking as 'dead' connection 'rOnowTW5RQ2kIp-Mj3_WjA'
2019-07-25T16:00:04.553Z elasticsearch Retrying request, there are still 0 attempts { method: 'HEAD',
  path: '/',
  body: null,
  querystring: '',
  headers:
   { 'User-Agent':
      'elasticsearch-js/6.8.1 (linux 4.15.0-54-generic-x64; Node.js v10.16.0)',
     'Accept-Encoding': 'gzip,deflate' },
  timeout: 300000 }
2019-07-25T16:00:04.553Z elasticsearch Starting a new request { method: 'HEAD', path: '/', timeout: 3000 }
2019-07-25T16:00:04.554Z elasticsearch qserialize 
2019-07-25T16:00:04.554Z elasticsearch Starting a new request { method: 'HEAD',
  path: '/',
  body: null,
  querystring: '',
  headers:
   { 'User-Agent':
      'elasticsearch-js/6.8.1 (linux 4.15.0-54-generic-x64; Node.js v10.16.0)',
     'Accept-Encoding': 'gzip,deflate' },
  timeout: 300000 }
2019-07-25T16:00:07.557Z elasticsearch Resurrect: connection '5_kS6iqtRf-2wI7Yja7NnQ' is still dead
2019-07-25T16:00:07.557Z elasticsearch Marking as 'dead' connection '5_kS6iqtRf-2wI7Yja7NnQ'
2019-07-25T16:00:07.558Z elasticsearch Request aborted { method: 'HEAD', path: '/', timeout: 3000 }
2019-07-25T16:02:15.624Z elasticsearch Marking as 'dead' connection '4aM2tEc4SnyZ9pYxBy9-uw'
(node:9242) UnhandledPromiseRejectionWarning: ConnectionError: connect ETIMEDOUT xx.xx.x.x:9200
    at onResponse (/home/jesse/Projects/QueryPark/Parsers/gos/node_modules/@elastic/elasticsearch/lib/Transport.js:220:13)
    at ClientRequest.request.on.err (/home/jesse/Projects/QueryPark/Parsers/gos/node_modules/@elastic/elasticsearch/lib/Connection.js:114:9)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:9242) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9242) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected behavior

I expect my connection to `http://localhost:9200` not to be closed and remain the only connection used.

## Your Environment

- *node version*: 10.16.0
- `@elastic/elasticsearch` *version*: ^6.6.0
- *os*: Linux
- *Elasticsearch version*: 6.x
- *GKE version*: 1.12.7-gke.25

Let me know what you think about this and if anything is missing.

**Comment by Jtaks** [comment]
Well I figured out what I was doing wrong. I assumed sniffing was just a check to see if the connection was valid. Turning off the sniffing feature removes the behaviour described above.

**Comment by and-kost** [comment]
@Jtaks thank you so much, turning off sniffing helped me! I faced the same issue with elastic in docker and my js app.
