### ISSUE TITLE
How to convert a dev tools query to a client query

### ISSUE THREAD

**Issue by microsoftly** [elastic/elasticsearch-js#943]
I'm attempting to convert a query I generated in the dev tools window in Kibana to a payload I can send with the ES client, but continuously get a 500 error, illegal_state_exception.

Any ideas on what it could be?

## Context
I fiddled around with what to put as parameters and where. I've settled with this below (which is roughly 1:1 the same as the payload that works in the dev tools window)
``` typescript 
const run = async () => {
  // @ts-ignore
  const result = await client.search({
    // @ts-ignore
    index: 'metadata',
    // @ts-ignore
    "_source": {
      "includes": ["fields.name"]
    },
    // @ts-ignore
    "source": {
      "includes": ["fields.name"]
    },
    "q": {
      "bool": {
        "filter": [
          {
            "bool": {
              "filter": [
                {
                  "bool": {
                    "should": [
                      {
                        "match_phrase": {
                          "severity": "error"
                        }
                      }
                    ],
                    "minimum_should_match": 1
                  }
                },
                {
                  "bool": {
                    "filter": [
                      {
                        "bool": {
                          "should": [
                            {
                              "match_phrase": {
                                "message": "Task finished"
                              }
                            }
                          ],
                          "minimum_should_match": 1
                        }
                      },
                      {
                        "bool": {
                          "should": [
                            {
                              "match_phrase": {
                                "fields.type": "maven"
                              }
                            }
                          ],
                          "minimum_should_match": 1
                        }
                      }
                    ]
                  }
                }
              ]
            }
          }
        ],
        "should": [],
        "must_not": [
          {
            "match_phrase": {
              "fields.stack": {
                "query": "error: duplicate key value violates unique constraint \"package_metadata_pkey\"\n    at Connection.parseE (/feonix/app/node_modules/pg/lib/connection.js:555:11)\n    at Connection.parseMessage (/feonix/app/node_modules/pg/lib/connection.js:380:19)\n    at Socket.<anonymous> (/feonix/app/node_modules/pg/lib/connection.js:120:22)\n    at Socket.emit (events.js:193:13)\n    at Socket.EventEmitter.emit (domain.js:481:20)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:276:11)\n    at Socket.Readable.push (_stream_readable.js:231:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:154:17)"
              }
            }
          }
        ]
      }
    }
  });

  console.log(JSON.stringify(result));
}

run()
  .then(() => console.log('done'))
  .catch(console.error);
```

**Comment by delvedor** [comment]
Hello! You should rename `q` to `body`.
`q` is querystring parameter that should be used only if you want to send the query with the Lucene syntax.
You are using Elasticsearch's DSL, which should be sent via body :)
